### ISSUE TITLE
Generate JSON Web Token (JWT) on Console

### ISSUE THREAD

**Issue by fmeschbe** [AdobeDocs/experience-platform.en#10]
Issue in ./help/landing/api-authentication.md

The guide indicates to use the Developer Console to generate the JSON Web Token (JWT). This is somewhat ok for testing and evaluation. But it is NOT ok for regular use. For regular use the JWT must be generated automatically. How this is done is well documented across the web and particularly here for Adobe: https://www.adobe.io/developer-console/docs/guides/authentication/JWT/

I propose you add a notice box to the guid indicating that this description is for tutorial, testing, and evaluation only and that JWT should actually be generated programmatically according to https://www.adobe.io/developer-console/docs/guides/authentication/JWT/

/cc @cxs504, @theManikJindal

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-114254.

**Comment by vgiurgiu** [comment]
The documentation has now been updated.

We have added a note to the appropriate section in the authentication tutorial: https://experienceleague.adobe.com/docs/experience-platform/landing/platform-apis/api-authentication.html#jwt
