### ISSUE TITLE
Number of edge segment not mentioned in Default guardrails

### ISSUE THREAD

**Issue by asha-pathik** [AdobeDocs/experience-platform.en#101]
Could you confirm the guardrails on number of Edge segments per sandbox. Default guardrails mention only streaming and batch. Is it a miss in the public docs?  
https://experienceleague.adobe.com/docs/experience-platform/profile/guardrails.html?lang=en

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-130128.

**Comment by vgiurgiu** [comment]
@asha-pathik - we have updated the guardrails with information on the number of Edge segments per sandbox. Thank you for reporting this. Closing the issue.
