### ISSUE TITLE
Explain the new syntax for cookie.set

### ISSUE THREAD

**Issue by morritza** [AdobeDocs/experience-platform.en#101]
Issue in ./help/tags/ui/client-side/satellite-object.md

Hi, could you please update the doc, the cookie set object needs some more explanation how to migrate from the old to new function:
New:
`
_satellite.cookie.set(“ew_adb002”,dateString,{expires:TimeTo});
`

Old:
`
_satellite.setCookie(“ew_adb002",dateString,TimeTo);
`

**Comment by djwendo** [comment]
Thank you for reporting this issue. We will review the documentation and make updates accordingly.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-102752

**Comment by djwendo** [comment]
The documentation has been updated and is now live on Experience League: https://experienceleague.adobe.com/docs/experience-platform/tags/client-side/satellite-object.html?lang=en#cookie
