### ISSUE TITLE
No archive button in the UI, but documentation refers to an archive button

### ISSUE THREAD

**Issue by selvarajadobe** [AdobeDocs/experience-platform.en#102]
Issue in ./help/dashboards/customize/custom-widgets.md

Archive a custom widget
After a widget has been added to the library, it can be archived using the Archive button. You can also edit the widget to update the title or description fields.

**Comment by djwendo** [comment]
Thank you for reporting this issue. We will review the documentation and update it shortly.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-102751

**Comment by djwendo** [comment]
The documentation has been updated and is now live on Experience League: https://experienceleague.adobe.com/docs/experience-platform/dashboards/customize/custom-widgets.html?lang=en#hide-a-custom-widget
