### ISSUE TITLE
Include details on export format and included fields

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#102]
Issue in ./help/destinations/destination-types.md

Can we include information about common fields and events that result in export messages for the different activation types?

For example for audience based destinations 
- Identity changes
- Audience membership changes - entries, exits along with their timestamp
- Changes to any field? when attributes are activated

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-130388.

**Comment by vfalon** [comment]
We've reviewed and updated the documentation to account for the suggested info. Closing this issue.
