### ISSUE TITLE
Can we provide detail on what components the TTL operates against.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#103]
Issue in ./help/hygiene/ui/ttl.md

Can we clarify in this doc if TTL operates against data lake, UIS, and UPS?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-130496.

**Comment by vfalon** [comment]
We've updated the docs to specify that dataset expirations are only marked as complete once they finish processing across data lake, Identity, and Profile: https://experienceleague.adobe.com/docs/experience-platform/hygiene/ui/dataset-expiration.html.

Closing this issue.
