### ISSUE TITLE
websdk link tracking

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/experience-platform.en#103]
Issue in ./help/edge/data-collection/track-links.md

the XDM in the code example is indented incorrectly. It should look like this:
alloy("sendEvent", {
    "xdm": {
        "web": {
            "webInteraction": {
                "linkClicks": {
                    "value": 1
                },
                "name": "My Custom Link", // Name that shows up in the custom links report
                "URL": "https://myurl.com", // The URL of the link
                "type": "other", // values: other, download, exit
            }
        }
    }
});

**Comment by djwendo** [comment]
Thank you for reporting this issue. We will review the documentation and update shortly.

Internal Tracking: https://jira.corp.adobe.com/browse/PLAT-102753

**Comment by djwendo** [comment]
The JavaScript syntax has been corrected and is now live on Experience League: https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/track-links.html
