### ISSUE TITLE
Link for Adobe Experience Platform debugger is wrong

### ISSUE THREAD

**Issue by immany** [AdobeDocs/experience-platform.en#105]
Issue in ./help/debugger/install-debugger.md
The Adobe Experience Platform Debugger link for chrome is https://chrome.google.com/webstore/detail/adobe-experience-cloud-de/ocdmogmohccmeicdhlhhgepeaijenapj, which is an old tool. The link should be https://chrome.google.com/webstore/detail/adobe-experience-platform/bfnnokhpnncpkdmbokanobigaccjkpob

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-130497.

**Comment by vfalon** [comment]
We've updated the documentation and the link should now point to the correct location. Closing this issue.
