### ISSUE TITLE
buildInfo.environment is deprecated

### ISSUE THREAD

**Issue by arobsco** [AdobeDocs/experience-platform.en#106]
Issue in https://github.com/AdobeDocs/experience-platform.en/blob/master/help/tags/ui/client-side/satellite-object.md#L211-L228

container.buildInfo.environment (https://experienceleague.adobe.com/docs/experience-platform/tags/client-side/satellite-object.html?lang=en#environment) is deprecated per console warning from Launch however no reference to this is made in the documentation. Can we please get a warning about this added to documentation as well as timescales for removal.

Additionally documentation around new environment property is also missing

**Comment by djwendo** [comment]
Thank you for reporting this issue.

We will review the documentation and update accordingly.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-104091

**Comment by djwendo** [comment]
The following documentation has been updated and the changes are now live:
https://experienceleague.adobe.com/docs/experience-platform/tags/client-side/satellite-object.html?lang=en#environment
https://experienceleague.adobe.com/docs/experience-platform/tags/extension-dev/turbine.html?lang=en#environment
