### ISSUE TITLE
How to specify a file

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#107]
Issue in ./help/ingestion/batch-ingestion/api-overview.md
It would be great to see an example of how {FILE_NAME} should look. What syntax/notation do I need to use to specify a file? Does the file need to be on my own hard drive? How will the API call know where to find it?   I searched and could not find any examples.  

I later saw this:  
{FILE_PATH_AND_NAME} | The full path and name of the file you are trying to upload. This file path is the local file path, such as Users/sample-user/Downloads/sample.json.

But the description of {FILE_NAME} "The name of the file you want to upload. This file path is the location where the file will be saved on the Adobe side." refers to a file path.  Is the name supposed to be both the file and the path?  And how would an end user know where the path will be saved "on the Adobe side"?  

Confusing!

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-131783.

**Comment by vfalon** [comment]
We've reviewed and updated the documentation. Closing this issue.
