### ISSUE TITLE
PATCH (and GET) API missing the tag "unifiedIdentity" for dataset to be enabled for profile

### ISSUE THREAD

**Issue by Sagho-adobe** [AdobeDocs/experience-platform.en#109]
Issue in ./help/catalog/datasets/enable-upsert.md

The documentation is missing setting the following tag to enable a dataset for profile-

"unifiedIdentity": [
"enabled:true"
]

Without this setting, in GUI of the dataset , the profile-enabled icon continues to show 'off/gray" 
![image](https://user-images.githubusercontent.com/112404672/187228607-446014ba-29df-411b-b71c-9f781e178d35.png)
...even when the patch API sets the following tags-
"unifiedProfile": [
"isUpsert:true",
"enabled:true"
],
On turning the toggle ON from GUI for the dataset, this 3rd tag gets set in addition to the two above.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-131782.

**Comment by vfalon** [comment]
The documentation was reviewed and updated accordingly. Closing this issue.
