### ISSUE TITLE
Adobe Tags or Tags in Adobe Experience Platform ?

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#11]
Issue in ./help/destinations/catalog/personalization/custom-personalization.md

This page mentions "Adobe Tags" but i think the name is "Tags in Adobe Experience Platform" as per the tags documentation

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-114793.

**Comment by vfalon** [comment]
We've updated the Tags naming and will close this issue. Thanks again for raising this!
