### ISSUE TITLE
Minor issue - Link to Schema Editor tutorial for easy navigation

### ISSUE THREAD

**Issue by vgiurgiu** [AdobeDocs/experience-platform.en#11]
Issue in help/xdm/schema/field-dictionary.md

On the [XDM field dictionary page](https://docs.adobe.com/content/help/en/experience-platform/xdm/schema/field-dictionary.html), there is the following sentence: 
"You can use the search functionality in the Schema Editor to view details of these resources, as shown in the Schema Editor tutorial."

Suggestion:
Link to the Schema editor, **Browse existing schemas in the Schemas workspace** section for easy navigation.

https://docs.adobe.com/content/help/en/experience-platform/xdm/tutorials/create-schema-ui.html#browse-existing-schemas-in-the-schemas-workspace

**Comment by djwendo** [comment]
@pnolan89 , I think a link may have been lost during migration. See above.

**Comment by djwendo** [comment]
Created a ticket to track: https://jira.corp.adobe.com/browse/PLAT-63635

**Comment by pnolan89** [comment]
This was addressed a while back in the following PR: https://git.corp.adobe.com/AdobeDocs/experience-platform.en/pull/738

Closing this issue.

**Comment by pnolan89** [comment]
Link has been updated: https://docs.adobe.com/content/help/en/experience-platform/xdm/schema/field-dictionary.html
