### ISSUE TITLE
Real time segment evaluation

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/experience-platform.en#112]
Issue in ./help/data-science-workspace/models-recipes/enrich-profile.md

Reading the first paragraph, seems that the outcome of a model is written into a dataset through the streaming pipeline, and so the segment is evaluated in near real-time every time the model exports a new output.

Can you please double check with the PM team? Because in my experience the output of the DSW is batch and so the segment is evaluated every 24 hrs.

Thanks

**Comment by angeli-adobe** [comment]
There is an ongoing discussion in PLATIR-22895.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-131781.

**Comment by angeli-adobe** [comment]
Hi, any updates?

**Comment by vfalon** [comment]
We've updated the docs and closing this issue.
