### ISSUE TITLE
Misleading info on immediate deletion of Profile

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-platform.en#114]
Issue in ./help/profile/privacy.md

https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html?lang=en#delete

as pet our doc

_The profile and its associated identity graph are immediately deleted as soon as Platform sends the confirmation that the deletion request was received._

I have randomly tested a few hundred privacy requests and can see that while the  identity graph is getting deleted almost immediately the profile cleanup is still in processing state after many hours. The profile is also accessible in the platform UI.

The doc needs correction to call this out and put a more realistic timeline around profile service.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-132421.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly. Closing this issue.
