### ISSUE TITLE
Repeated text

### ISSUE THREAD

**Issue by georgesavill** [AdobeDocs/experience-platform.en#115]
Issue in ./help/destinations/catalog/advertising/facebook-pixel.md

You have repeated some text in the Prerequisites section:
_Contact your organization administrator to get access to tags and ask them to grant you the manage_properties permission so you can install extensions. and ask them to grant you the manage_properties permission so you can install extensions._

**Comment by vgiurgiu** [comment]
@georgesavill , thank you for reporting this. We have now updated the documentation to correct the error you spotted. 

Best regards! 
Victor
