### ISSUE TITLE
Additional information for profile ingestion guardrails

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#115]
Issue in ./help/ingestion/guardrails.md

This page has some information for profile ingestion guardrails. But it does not include the recommended # of batches for profile ingestion that is found on the profile guardrails page here - https://experienceleague.adobe.com/docs/experience-platform/profile/guardrails.html?lang=en#:~:text=affect%20system%20performance.-,Number%20of%20Profile%20or%20ExperienceEvent%20batches%20ingested%20per%20day,-90

I suggest we also add the number of batches for profile ingestion guardrail to this page as well so both pages provide consistent guidance.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-132422.

**Comment by vgiurgiu** [comment]
@nhecht - we've updated the documentation as required. Guidance on the number of batches for profile ingestion has been added to the guardrails for ingestion doc here: https://experienceleague.corp.adobe.com/docs/experience-platform/ingestion/guardrails.html 

Thanks for flagging this! Closing the issue.
