### ISSUE TITLE
guardrails on number of records per second streaming that profile can ingest.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#116]
Issue in ./help/profile/guardrails.md

Is there any guardrail on the number of records per second streaming that profile can ingest?
If so, can we add it to this page.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-132424.

**Comment by vfalon** [comment]
We've reviewed and updated the documentation. Closing this ticket.
