### ISSUE TITLE
Edge and Streaming event guardrails

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#117]
Issue in ./help/profile/guardrails.md

Per the product description - https://helpx.adobe.com/legal/product-descriptions/real-time-customer-data-platform.html
both edge and streaming segmentation have a limit of 1500 rps. 
Can we add this to the experience league guardrails page?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-132425.

**Comment by vfalon** [comment]
We've updated the documentation with the correct value. Closing this issue.
