### ISSUE TITLE
Update Existing Only?

### ISSUE THREAD

**Issue by preymond** [AdobeDocs/experience-platform.en#12]
Issue in ./help/destinations/catalog/mobile-engagement/braze.md

Does this integration set the _update_existing_only flag to true? Curious if we can create net new users in Braze or if it is being limited to existing users only.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-114794.

**Comment by vfalon** [comment]
@preymond since this aspect of the Braze integration is closer tied to the inner workings of the Braze platform than Experience Platform, we recommend getting in touch with Braze for as accurate an answer as possible. Closing this issue.
