### ISSUE TITLE
Non-expiring credentials

### ISSUE THREAD

**Issue by renright-TAM** [AdobeDocs/experience-platform.en#120]
Issue in ./help/query-service/ui/credentials.md

Please add in the fact that for non-expiring credentials you need to use the following format for the password --> <technicalAccountId>colon<credential> otherwise the non-expiring credentials won't work.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-134246.

**Comment by vgiurgiu** [comment]
@renright-TAM - we have updated the note on
https://experienceleague.adobe.com/docs/experience-platform/query/ui/credentials.html?lang=en#using-credentials-to-connect-to-external-clients

with additional information, as requested. Closing this issue, please re-open if you need us to make further updates.
