### ISSUE TITLE
SHA256 referenced page - possible wrong reference

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#122]
Hey team.
About the allowed identity namespace.
In the description of the Emails SHA256 a link is pointing to a document supposed to provide more details about the SHA256 hashing support. The link actually points to the [setCustomerID method](https://experienceleague.adobe.com/docs/id-service/using/reference/hashing-support.html?lang=en#hashing-support) of the Visitor ID Service.

 Is this actually the meant reference? The AEP implementation best practices involves the Web SDK, not the Visitor ID Service APIs.
 Mind to check if that is the right link?

Issue in ./help/segmentation/ui/segment-match/overview.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-134245.

**Comment by vgiurgiu** [comment]
Hi @decaroa - we updated the [Set up identity data and namespaces](https://experienceleague.adobe.com/docs/experience-platform/segmentation/ui/segment-match/overview.html?lang=en#namespaces) section of the page you pointed out. 

As per instructions from our Product Manager, we added a link to the data prep hashing function and kept the setCustomerId link as well. 

Closing this issue.
