### ISSUE TITLE
Segment membership status

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#125]
Issue in ./help/destinations/ui/activate-batch-profile-destinations.md

This talks about segment membership status being able to be selected as a activation attribute, but I don't think that attribute can be selected in the activation flow as it is in a map field and the UI does not allow selection of it.

"If the segmentMembership.status field is not selected, exported files include only Active members in the initial full snapshot and in subsequent incremental exports."

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-135122.

**Comment by vgiurgiu** [comment]
We have documented the known limitation that segment membership status cannot be selected using the Select field menu, as well as the current workaround suggested by our Engineering team. 

Please see:
https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-batch-profile-destinations.html#select-attributes

Closing this issue.

**Comment by vgiurgiu** [comment]
We have documented the known limitation that segment membership status cannot be selected using the Select field menu, as well as the current workaround suggested by our Engineering team. 

Please see:
https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-batch-profile-destinations.html#select-attributes

Closing this issue.
