### ISSUE TITLE
Need to know guardrails for Edge segmentation

### ISSUE THREAD

**Issue by Lexieyw** [AdobeDocs/experience-platform.en#126]
Issue in ./help/profile/guardrails.md

There is no guardrails for edge segementation. Need that information.

**Comment by vgiurgiu** [comment]
Thank you for reporting this issue. We are already tracking the issue about missing guardrails for edge segments in the internal issue PLAT-130128. 

We're looking to update the documentation as soon as possible.

**Comment by vgiurgiu** [comment]
@Lexieyw - we have updated the guardrails with information on the number of Edge segments per sandbox. Thank you for reporting this. Closing the issue.
