### ISSUE TITLE
Gtag Extension is discontinued

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/experience-platform.en#127]
Issue in ./help/destinations/catalog/advertising/gtag-advertising.md

The Gtag extension is marked as discontinued, and throws an error when trying to configure.

Please update the documentation at: https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/gtag-advertising.html?lang=en and https://exchange.adobe.com/apps/ec/102805/google-gtag

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-135379.

**Comment by vfalon** [comment]
We've updated the documentation to reflect the changes. Closing this issue.
