### ISSUE TITLE
Feature not working as expected - engineering reporting the feature is not available.

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#128]
Hey team. I have been supporting a client on the implementation of the consent management based on this article.
After discovering it's not working, we raised a [ticket](https://jira.corp.adobe.com/browse/PLATIR-23770). One of the engineers stating:
"Unfortunately this is not something technically possible at the moment".

I assume the process described in the article has been tested before documenting it.
Could you please confirm the consent management is working as expected and documented?

Thanks!!

Issue in ./help/landing/governance-privacy-security/consent/adobe/overview.md

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-135353.

**Comment by vfalon** [comment]
Closing this issue due to lack of information. We'll revisit it if needed.
