### ISSUE TITLE
Documentation is incomplete.

### ISSUE THREAD

**Issue by ankurmehrotra** [AdobeDocs/experience-platform.en#13]
Issue in ./help/segmentation/tutorials/using-external-audiences.md

1. The documentation says that "With the dataset enabled, data can now be sent into Platform either through the UI ". This is not true for streaming ingestion. 
2. Internal Wiki document gives an example of a call which refers EntityUpdate within the POST request, when one has to mark a segmentMap on the profile. This is not explained or even indicated.
3. The page also fails to indicate what must be done (SegmentationMap) on the profile for it to work. It would have been nice to pick an example with data structures and show how it lands.
4. The document does not indicate how will exits and entries of segment behave. This is a standard need of the use cases and should be indicated.

Internal reference: https://wiki.corp.adobe.com/display/DMSArchitecture/Importing+and+using+External+Audiences

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-114873.

**Comment by vfalon** [comment]
@ankurmehrotra The documentation was reviewed and multiple updates were done by the team. Closing this issue.
