### ISSUE TITLE
Date for latest release 5.2.1 incorrectly states Nov 3, 2020

### ISSUE THREAD

**Issue by mpspencer** [AdobeDocs/experience-platform.en#130]
Issue in ./help/tags/extensions/web/id-service/release-notes.md

**Comment by djwendo** [comment]
Tracking internally: https://jira.corp.adobe.com/browse/PLAT-110668

**Comment by djwendo** [comment]
Date has been fixed. https://experienceleague.adobe.com/docs/experience-platform/tags/extensions/adobe/id-service/release-notes.html
