### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#130]
Issue in ./help/xdm/field-groups/profile/identitymap.md

Based on customer implementations this warning should be removed, customers frequently use the identity map field for setting identity and altering which identity namespace is set as primary. 

"The IdentityMap field is automatically updated by the system as identity data is ingested. In order to properly utilize this field for [Real-time Customer Profile](https://experienceleague.adobe.com/docs/experience-platform/profile/home.html?lang=en), do not attempt to manually update the field’s contents in your data operations."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-136925.

**Comment by vfalon** [comment]
We've reviewed the documentation and removed the note. Closing this issue.
