### ISSUE TITLE
Wrong property name

### ISSUE THREAD

**Issue by woolleyadobe** [AdobeDocs/experience-platform.en#131]
The property name should be `partialIngestionPercent` _not_ `partialIngestionPercentage`

Issue in ./help/ingestion/batch-ingestion/partial.md

**Comment by djwendo** [comment]
Tracking internally: https://jira.corp.adobe.com/browse/PLAT-110669

**Comment by djwendo** [comment]
Update has been made and merged. Changes should appear on Experience League once the publishing cycle completes.

https://experienceleague.adobe.com/docs/experience-platform/ingestion/batch/partial.html?lang=en
