### ISSUE TITLE
Updating Release notes to Include Experience Cloud ID Service Extension 5.5.0.

### ISSUE THREAD

**Issue by hmroczek** [AdobeDocs/experience-platform.en#133]
Issue in ./help/tags/extensions/web/id-service/release-notes.md

Hi team,

the new upgrade for ECID service extension is available but now info has been included in Release Notes. 

Can we have this article updated to include changes in this upgrade?

Best,

Hanna

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-136924.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the required updates (https://experienceleague.corp.adobe.com/docs/experience-platform/tags/extensions/adobe/id-service/release-notes.html#oct-17%2C-2022). Closing this issue.
