### ISSUE TITLE
sample query to download query results to local machine

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#134]
Issue in ./help/query-service/sql/overview.md

Can we add a sample query for how a user can download the query results of an interactive query to their local machine. In like a CSV file.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137518.

**Comment by vfalon** [comment]
The suggested information is available here https://experienceleague.adobe.com/docs/experience-platform/query/troubleshooting-guide.html?lang=en#export-csv. Closing this issue.
