### ISSUE TITLE
Slight typo in the examples

### ISSUE THREAD

**Issue by georgerht** [AdobeDocs/experience-platform.en#134]
Issue in ./help/edge/data-collection/collect-commerce-data.md
![image](https://user-images.githubusercontent.com/32357878/140911131-85d569dc-0a2a-4807-8fbb-6e7f057b6f08.png)

**Comment by djwendo** [comment]
Thank you for reporting this issue. We are reviewing the documentation and will update accordingly.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-110689

**Comment by djwendo** [comment]
Documentation has been updated.
https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/collect-commerce-data.html?lang=en#examples
