### ISSUE TITLE
eventType should be  "homePageView" instead of  "addToCart"

### ISSUE THREAD

**Issue by vishalwani** [AdobeDocs/experience-platform.en#135]
Issue in ./help/segmentation/ui/edge-segmentation.md

In Supported query type example you have: 

Single event that refers to a profile | Any segment definition that refers to one or more profile attributes and a single incoming event with no time restriction. | People who live in the USA that visited the homepage. | homeAddress.countryCode = "US" and chain(xEvent, timestamp, [A: WHAT(eventType = "addToCart")])
-- | -- | -- | --
 for the last one eventType shouldn't be "addToCart" instead it should be "homePageView"?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137519.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly. Closing this issue.
