### ISSUE TITLE
Select the identity

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/experience-platform.en#136]
Issue in ./help/destinations/catalog/advertising/google-dv360.md
In the table "Supported identities", in the column "Considerations" there some sentences starting with: "Select this target identity...". 
I went through the setup process for the destination and there is no way to select the identity. What does this sentence ""Select this target identity...", means? Where should I select the identity?

Thanks

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137520.

**Comment by vfalon** [comment]
We've reviewed the docs and updated the phrasing to reflect the correct workflow. Closing this issue.
