### ISSUE TITLE
Please add release notes for v1.8.8

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/experience-platform.en#136]
Issue in ./help/tags/extensions/web/analytics/release-notes.md

Hello,

The release notes page has information up to version 1.8.7 but the currently available version in Adobe Launch is 1.8.8

REF: https://experienceleague.adobe.com/docs/experience-platform/tags/extensions/adobe/analytics/release-notes.html?lang=en

**Comment by djwendo** [comment]
Thank you for logging this issue. We are reviewing the documentation and will update accordingly.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-110815

**Comment by Brontojoris** [comment]
This done.
