### ISSUE TITLE
Dataset Expirations Wording in Data Hygiene 

### ISSUE THREAD

**Issue by rmacrae-at-adobe-com** [AdobeDocs/experience-platform.en#137]
Issue in ./help/hygiene/home.md

Under "Dataset expirations" the Description" for "Segments updated" reads "Once **profiles** are removed, all related [segments](https://experienceleague.adobe.com/docs/experience-platform/segmentation/home.html?lang=en) are updated to reflect their new size." 

"profiles" are not being removed, **datasets** are being removed.  Hence the wording here could be confusing.  It's conceivable that a profile will be removed if all data that belongs to it was received only in the dataset that's being deleted, but this won't always be be the case.  Also, the removal of a dataset could change the size of a segment by other means than profile removal.  Depending on the dataset being removed, a segment could conceivably increase in size.

I believe this should be reworded to: 

**Once the dataset has been removed, and all affected profiles have been updated**, all related [segments](https://experienceleague.adobe.com/docs/experience-platform/segmentation/home.html?lang=en) are updated to reflect their new size."

Thanks.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137522.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly. Closing this issue.
