### ISSUE TITLE
When active is activated

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#138]
Issue in ./help/destinations/ui/activate-batch-profile-destinations.md

"If the segmentMembership.status field is selected, exported files include Active members in the initial full snapshot and Active and Expired members in subsequent incremental exports."

Should this line rather say, "... and NEWLY Active and Expired members in subsequent incremental exports."

Meaning it does not activate every profile in active or expired state, but only the profiles that are "Newly" active or expired as of the last incremental activation.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137523.

**Comment by vfalon** [comment]
Closing this issue, as the documentation was updated.
