### ISSUE TITLE
Wrong href value: "destination testing tool" pointing to message creation.

### ISSUE THREAD

**Issue by alberto-decaro** [AdobeDocs/experience-platform.en#139]
Issue in ./help/destinations/destination-sdk/configure-destination-instructions.md

The following link in the section 6 is assumed to point to the destination testing tool:
![image](https://user-images.githubusercontent.com/2655809/142864355-9efba927-ecb2-4917-9f89-7d99c213fbfc.png)

Actually the href is: https://experienceleague.adobe.com/docs/experience-platform/destinations/destination-sdk/functionality/developer-tools/create-template.html?lang=en
I assume the correct href value is: https://experienceleague.adobe.com/docs/experience-platform/destinations/destination-sdk/functionality/developer-tools/test-destination.html?lang=en

Do you mind to check?
Thanks,
Alberto

**Comment by vgiurgiu** [comment]
Thank you for logging this issue. 

> I assume the correct href value is: https://experienceleague.adobe.com/docs/experience-platform/destinations/destination-sdk/functionality/developer-tools/test-destination.html?lang=en

That is correct. We will update the documentation shortly.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-110690

**Comment by vgiurgiu** [comment]
Step 6 now includes the correct link to the destination testing tool: 
https://experienceleague.adobe.com/docs/experience-platform/destinations/destination-sdk/guides/configure-destination-instructions.html?lang=en#test-destination

Thanks again for reporting the issue!
