### ISSUE TITLE
Does activation also happen when a profile changes from "entered" to "Existing" status?

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#139]
Issue in ./help/destinations/ui/activate-batch-profile-destinations.md

Can we clarify in the docs when a profile goes from "entered" to "Existing" segment status - is a record activated? Or is a record only activated when a user goes from null to "entered"?

"If the segmentMembership.status field is selected, exported files include Active members in the initial full snapshot and Active and Expired members in subsequent incremental exports."
"If the segmentMembership.status field is not selected, exported files include only Active members in the initial full snapshot and in subsequent incremental exports."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137525.

**Comment by vfalon** [comment]
We've reviewed the documentation and the existing status has now been deprecated. The two remaining segmentMembership statuses are realized and exited, as can be seen here:

https://experienceleague.adobe.com/docs/experience-platform/xdm/field-groups/profile/segmentation.html?lang=en

Closing this issue.
