### ISSUE TITLE
Missing release notes for v'1.8.9'

### ISSUE THREAD

**Issue by mpspencer** [AdobeDocs/experience-platform.en#14]
Issue in ./help/tags/extensions/web/analytics/release-notes.md

Missing release notes for v'1.8.9'

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-114874.

**Comment by vfalon** [comment]
Analytics release notes have been updated to 1.9.0. Closing this issue.
