### ISSUE TITLE
Please Add Google UI Update time

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/experience-platform.en#140]
Issue in ./help/destinations/catalog/advertising/google-ad-manager.md

In helping a customer through an issue on this integration, I learned from the Google team that it takes 24-48 hours before audience numbers will show up in the Google Ad Manager UI. So after users map an AEP segment to this destination, the segment name will appear immediately in the GAM UI, but the population won't appear until at least 24 (and likely 48) hours later. Additionally, we need an audience size of at least 50 before it'll show, so be wary of using test segments with just a handful of profiles. Can we update this page with these two additional points of information? Thanks!

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137524.

**Comment by vfalon** [comment]
We've updated the documentation to reflect this behavior. Thanks for raising this! I'll close this issue now.

**Comment by dhwoolsey** [comment]
Thanks! Looks great!
