### ISSUE TITLE
Update link for "tags extension"

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#141]
Issue in ./help/edge/home.md

The first link on this page is about the "tags extension". The link takes you to a page in the tags documentation, which basically just has a link back to the web sdk documentation. Perhaps the link on this page should just go directly to: https://experienceleague.adobe.com/docs/experience-platform/edge/extension/web-sdk-extension-configuration.html?lang=en

**Comment by djwendo** [comment]
Thanks for logging this issue. We will review the documentation and update accordingly.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-111397

**Comment by djwendo** [comment]
Documentation has been updated: https://experienceleague.adobe.com/docs/experience-platform/edge/home.html
