### ISSUE TITLE
table of core labels is missing C12

### ISSUE THREAD

**Issue by qualitybydesign** [AdobeDocs/experience-platform.en#141]
Issue in ./help/data-governance/labels/reference.md

table and appendix for contract labels only include up to C11.  there is now a C12 label.

```
 "name": "C12",
  "category": "Contract",
  "friendlyName": "No General Data Export",
  "description": "Data cannot be exported in any way."
```

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137526.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly. Closing this issue.
