### ISSUE TITLE
clarify user label type selection in policy creation

### ISSUE THREAD

**Issue by qualitybydesign** [AdobeDocs/experience-platform.en#143]
Issue in ./help/access-control/abac/ui/policies.md

I suggest clarifying the instructions by changing

   `Next, using the dropdown, select the **User**.`

to something like:

   `Next, using the dropdown, select the type of labels (Core or Custom) to match against the labels in the roles assigned to the **User**.`

Also,  update the screenshot to show both `Core Label` and `Custom Label` in the pulldown

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137527.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly. Closing this issue.
