### ISSUE TITLE
Allow listing is self-serve. No need to contact Google

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/experience-platform.en#146]
Issue in ./help/destinations/catalog/advertising/google-ad-manager.md

After working through a couple of Google issues, I've learned that the Allow-listing needed can all be done by the customer without contacting Google. So instead of the Blue notes box or the paragraph header stating that the customer needs to reach out to Google to be put on the allow list, customers simply need to do the following 2 things:

First, visit the Google help center here: https://support.google.com/admanager/answer/3289669?hl=en and follow the steps to add Adobe as a linked DMP (applies for both AAM and AEP).

Second, they need to go to Admin > Global Settings > Network Settings and enable the API Access slider.

That second one is one that they could do while they are getting their audience link code as well (a few steps further down in the instructions). Not sure how/if you want to combine the two instructions, but yeah....they need to do both.

By updating this doc with this information, we can skip a few days of troubleshooting while trying to get hold of a Google rep only to find out they could have done this themselves :).

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137906.

**Comment by vfalon** [comment]
Documentation was updated with the correct allow-listing process. Closing this issue.
