### ISSUE TITLE
Additional ID Sync Instructions needed

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/experience-platform.en#147]
Issue in ./help/destinations/catalog/overview.md

This bit of feedback applies to 5 destinations within this section, so I'm logging this here on the upper level, but it applies to the following 5 destinations:

Googls Ads Destination:
https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/google-ads-destination.html?lang=en

Google Ads Manager
https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/google-ad-manager.html?lang=en

Google Display & Video 360 connection
https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/google-dv360.html?lang=en

Microsof Bing
https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/bing.html?lang=en

The Trade Desk
https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/tradedesk.html?lang=en

Each of these destinations has a brown/orange box that mentions the need for an ID sync and instructions to have support enable it. It also mentions that this carries over from any AAM destinations with the same partner. All of that is mostly true. However, if a customer is using the Web SDK on their site to replace Visitor ID service, then they also need to allow the ID syncing to happen on their site (in addition to having customer care enable it). 

So, if the customer is using AEP Web SDK and legacy Visitor ID service is not on the page, then they need to ensure that the data stream for the site in question is enabled to allow for 3rd Party ID syncing as outlined here:

https://experienceleague.adobe.com/docs/experience-platform/edge/datastreams/configure.html?lang=en

They need to ensure that the Third Party ID Sync slider is enabled. Most customers would leave the container_id blank (it will default to 0). They only need to change that if their legacy AAM implementation used a specific container ID (it would be the vast minority of customers). 

Once that is enabled, and the Id sync is enabled by Customer Care, then the customer will see new network requests on their site to the demdex.net domain as well as to a domain belonging to the partner destination (for example, Google ID syncs also generate a network call to google.com).

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-137907.

**Comment by vfalon** [comment]
We've reviewed and updated the docs to better explain the ID sync process:https://experienceleague.adobe.com/docs/experience-platform/destinations/how-destinations-work/identity-handling.html?lang=en#third-party-cookie-destinations. Closing this issue.
