### ISSUE TITLE
change log not updated since Feb 2021?

### ISSUE THREAD

**Issue by vishalwani** [AdobeDocs/experience-platform.en#149]
Issue in ./help/identity-service/ui/identity-graph-viewer.md
Looks like change log on this page is not updated since Feb 2021? Is that accurate?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-139295.

**Comment by vfalon** [comment]
We've reviewed the documentation and the changelog is accurate. Closing this issue.
