### ISSUE TITLE
This document reverences Azure when it is for Google

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#152]
Issue in ./help/sources/connectors/cloud-storage/google-pubsub.md

"Platform allows you to bring in data from Azure Event Hubs in real time."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-139296.

**Comment by vfalon** [comment]
We've updated the documentation to mention the correct name. Closing this issue.
