### ISSUE TITLE
Will deleting a batch from a dataset with profile enabled also delete the batch from profile.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#155]
Issue in ./help/catalog/datasets/user-guide.md

Add information on whether deletion of a batch will result in the batch being deleted from profile as well.

"If you wish to delete the batch, you can do so by selecting Delete batch found near the top right of the dashboard. Doing so will also remove its records from the dataset the batch was originally ingested to."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-139618.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the necessary updates. Closing this issue.
