### ISSUE TITLE
Out-of-date copy

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#156]
Issue in ./help/edge/fundamentals/tracking-events.md

This sentence is out-of-date--the future is here! Also, it should include an example.
"In the future, you will be able to send your full data layer under the data option and map it to XDM server-side."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-139617.

**Comment by vfalon** [comment]
The recent Web SDK docs revamp covered this in the new sendEvent section and the child pages: https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/commands/sendevent/overview.

Closing this issue.
