### ISSUE TITLE
why is email shown as mapped twice

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#157]
Issue in ./help/destinations/catalog/advertising/google-customer-match.md

In the image below it shows email mapped from ID map and from a standard email field. 

https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/google-customer-match.html?lang=en#:~:text=Select%20the%20Email_LC_SHA256%20namespace%20as%20source%20identity%20if%20you%20hashed%20customer%20email%20addresses%20on%20data%20ingestion%20into%20Platform%2C%20according%20to%20Google%20Customer%20Match%20email%20hashing%20requirements.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140469.

**Comment by vfalon** [comment]
We've reviewed and updated the screenshot for better clarity. Closing this issue.
