### ISSUE TITLE
Tags instead of launch

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#158]
Issue in ./help/edge/fundamentals/installing-the-sdk.md
Instead of "For documentation on the tag extension, see the launch documentation" shouldn't this say "see the tags documentation"?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140470.

**Comment by vfalon** [comment]
We've updated the documentation accordingly. Closing this issue.
