### ISSUE TITLE
URL incorrect

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#159]
Issue in ./help/sources/tutorials/api/create/cloud-storage/data-landing-zone.md

Add "data/foundation/" to the URL GET /connectors/landingzone?type=user_drop_zone.
The example uses the correct URL, but the text doesn't!

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140471.

**Comment by vfalon** [comment]
We've reviewed the documentation and fixed the URL. Closing this issue.
