### ISSUE TITLE
Datastream environment and AEP sandbox

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/experience-platform.en#16]
Issue in ./help/edge/fundamentals/datastreams.md

About "Adobe Experience Platform settings" section: it seems that there a 1:1 correlation between datastream and sandbox. Once the datastream is setup, each environment can be setup in different way, but the sandbox is not editable (see screenshot).
If this is the expected behaviour, can you please specify in the documentation?

![image](https://user-images.githubusercontent.com/72991519/153186537-d3e7409a-3b8f-4270-9229-9dc952fee8d5.png)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-115695.

**Comment by vfalon** [comment]
@angeli-adobe We have reviewed the documentation and the behavior you mentioned is correct. Sandboxes are not editable when editing existing datastreams. This is already mentioned in the documentation, in the Adobe Experience Platform settings table, at the Sandbox description:

"(Required) Select the Platform sandbox that you want to send data to. Sandboxes are virtual partitions in Adobe Experience Platform that allow you to isolate your data and implementations from others in your organization.

Once a datastream is created, its sandbox cannot be changed. The Sandbox selection field is therefore unavailable when editing an existing datastream."

Closing the issue.

**Comment by angeli-adobe** [comment]
Thanks @vfalon ! This is not 100% correct.
If you create the datastream and you don't enable "adobe experience platform" and save it, then you can open each environment and select the sandbox you want and change it anytime. This is something that should be documented as well. 

![image](https://user-images.githubusercontent.com/72991519/155128918-5fd15837-5a55-4274-8cb6-e04ca175345d.png)

Let me know if you need more details.
Best,
Alberto
