### ISSUE TITLE
There should be generic instructions for connecting to DLZ

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#160]
Issue in ./help/sources/tutorials/api/create/cloud-storage/data-landing-zone.md

The instructions on how to connect to DLZ were written from the source connector perspective, but now that the destination is there (still in beta), it would be better to include the list of valid "type=" options on the same page.  
Currently the (beta) DLZ dataset destinations instructions are a little confusing, because you have to follow instructions to connect from the DLZ source connector page, and it's easy to miss the right connector type (I thought the destination wasn't working but with some digging I figured out that I just needed a different credential to see it).

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140472.

**Comment by vfalon** [comment]
We've updated the documentation with clearer information. Closing this issue.
