### ISSUE TITLE
Apply response and Redirect with Identity

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#161]
Issue in ./help/edge/extension/action-types.md

There are new action types for "Apply response" and "Redirect with identity". Can you please add documentation and examples of what these new actions do?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140473.

**Comment by vfalon** [comment]
We've added more information about the specified action types. Closing this issue.
