### ISSUE TITLE
Additional text for the "Note"

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#162]
Issue in ./help/access-control/abac/ui/labels.md

User must have Product Admin rights and access to the default "prod" sandbox.  Pls check with Sal Daoud to see whether this is still the case.  If this stays the case, you want to mention this in the docs to avoid that people open tickets.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140474.

**Comment by vfalon** [comment]
We've investigated this issue and the access control team has confirmed that "User must have Product Admin rights and access to the default "prod" sandbox." is incorrect. Closing this issue.
