### ISSUE TITLE
Double negative

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#163]
Issue in ./help/access-control/abac/end-to-end-guide.md

Text states "This will deny access to the schema field and segment in all sandboxes for users who do not have matching labels."
Why the double negative??

How about:
This will grant access to the schema field and segment in all sandboxes for users who have matching labels.  

Just a suggestion.  Otherwise it's like doing a puzzle to figure out what is meant! 

--Amy

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140475.

**Comment by hbhandal80** [comment]
@vfalon This issue can be closed. Document has been updated.
