### ISSUE TITLE
Mismatch between text and screenshot

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#17]
Issue in ./help/xdm/tutorials/relationship-ui.md

The text says "The updated "loyaltyRelationship" field appears in the canvas" but in the screenshot the field is named "favoriteHotel"

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-63526

**Comment by pnolan89** [comment]
Doc has been updated: https://docs.adobe.com/content/help/en/experience-platform/xdm/tutorials/relationship-ui.html
