### ISSUE TITLE
General API guide feedback

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#17]
Issue in ./help/query-service/api/queries.md
I get a postman error and I cannot find any documentation on Adobe that tells me what to do.

"There was an error in evaluating the Pre-request Script:TypeError: Cannot read property 'value' of undefined"

There are 2 new header vars added x-request-id and User-Agent and I cannot figure out what I need to do to get the query API calls to work as the commands don't get past the pre-request script.  I cannot find documentation that tells me how these fields can get set or how I can resolve this error.  

It would be good if this error would be more specific - like if the pre-script would tell you that it's missing a certain value as an environment variable, as this error is very generic. 

I searched on Exp League for the error message, but it doesn't find anything.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-116109.

**Comment by vfalon** [comment]
Closing this issue based on internal assessment.
