### ISSUE TITLE
Update Important note

### ISSUE THREAD

**Issue by luke-penrod** [AdobeDocs/experience-platform.en#170]
Issue in ./help/tags/extensions/client/media-analytics-3x/overview.md

Please update the Important note on this page to read: 
This extension deploys with Media 3.x SDK, which is not backward compatible with Media 2.x SDK. Because Media 2.x. SDK is deprecated, please update to Media 3.x SDK.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-140476.

**Comment by vfalon** [comment]
We've updated the documentation accordingly. Closing this issue.
