### ISSUE TITLE
Is there a maximum number of records or payload size guardrail for this capability

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#173]
Issue in ./help/server-api/non-interactive-data-collection.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-145022.

**Comment by vfalon** [comment]
@nhecht the Server API guardrails are described in this page: https://experienceleague.adobe.com/en/docs/experience-platform/edge-network-server-api/guardrails. See the https://experienceleague.adobe.com/en/docs/experience-platform/edge-network-server-api/guardrails#service-limits section.
