### ISSUE TITLE
What does this phrase mean?

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#177]
Issue in ./help/segmentation/ui/streaming-segmentation.md

"In the case of a profile event, however, it must wait 24 hours to be incorporated."

Can additional context be added. I am not sure what a "profile event" is.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-145023.

**Comment by vfalon** [comment]
The documentation was updated to refer to a profile attribute instead of a profile event.
