### ISSUE TITLE
link issues

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/experience-platform.en#18]
Issue in ./help/destinations/catalog/personalization/adobe-target-connection.md

Just above the "connection parameters" section this sentence appears to have a link that isn't clickable: To connect to this destination, follow the steps described in the [destination configuration tutorial](/docs/experience-platform/destinations/ui/connect-destination.html?lang=en).

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-116110.

**Comment by vfalon** [comment]
The link is fixed now. Closing the issue.
