### ISSUE TITLE
LiveFyre is End of Life - Please delete this content

### ISSUE THREAD

**Issue by TylerRush** [AdobeDocs/experience-platform.en#187]
Issue in ./help/destinations/catalog/social/adobe-livefyre.md

I am working with PM to remove all content referencing LiveFyre. Can someone who has write permission on this repo remove this file? Thank you.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-147094.

**Comment by vfalon** [comment]
We've removed the outdated content. Closing this issue.
