### ISSUE TITLE
(Beta) Experience Cloud Audiences connection - conflicting/unclear statement in the pre-requisite section

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#189]
Issue in ./help/destinations/catalog/adobe/experience-cloud-audiences.md

Good day team.
I appreciate a confusing statement in the pre-requisite section of the document.
- The 2nd bullet states "You need an Audience Manager license to enable the Data Management Platform use cases mentioned in the section above".
- The section above is actually listing Adobe Campaign, Adobe Target, Advertising Cloud, Analytics, Marketo.

Hence the conclusion would be that I need and Audience Manager license to share audiences to those solutions.

But then the 3rd bullet in the pre-requisites states:
- "You do not need an Audience Manager license to share Experience Platform segments with Adobe Advertising Cloud, Adobe Target, Marketo, and other Experience Cloud solutions, via the Experience Cloud Audiences integration"

At this point it is not clear if the Audience Manager license is required or not to share audiences to those destinations.
Could you please review the pre-requisites?

Thanks!!
Alberto

![image](https://user-images.githubusercontent.com/100088147/223661519-8a5076c1-0038-4bc7-8545-b8732b0c333c.png)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-149338.

**Comment by vfalon** [comment]
We've reviewed the docs and made the required updates. Closing this issue. Thanks!
