### ISSUE TITLE
How to load data from profile to datasets 

### ISSUE THREAD

**Issue by nimbalkarnarendra1** [AdobeDocs/experience-platform.en#19]
Hi Team,
Greetings !
can you please guide me, How to load data from profile to datasets  in adobe experience platform

Thank-you so much in advance !!!

**Comment by vfalon** [comment]
Thank you for reaching out! Please go through the following docs for a better understanding of how to configure datasets:

- https://experienceleague.adobe.com/docs/experience-platform/catalog/datasets/user-guide.html?lang=en
- https://experienceleague.adobe.com/docs/experience-platform/catalog/datasets/create.html?lang=en
- https://experienceleague.adobe.com/docs/experience-platform/catalog/datasets/enable-for-profile.html?lang=en
