### ISSUE TITLE
Streaming Segment guidance

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#190]
Issue in ./help/segmentation/ui/streaming-segmentation.md

Confirmed with engineering that the below quoted content is not accurate. According to engineering in segment queries can include both events and profile attributes and as long as the final analyzed event or segment is a streaming event then the segment will qualify and be evaluated for streaming segmentation.
It would also be helpful to put this information in a cell in the table line item, vs. down below the table where a reader may miss it.

"A segment definition will not be enabled for streaming segmentation in the following scenarios:
"The segment definition includes a combination of a single event and an inSegment event.
However, if the segment contained in the inSegment event is profile only, the segment definition will be enabled for streaming segmentation."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-149339.

**Comment by vfalon** [comment]
We've reviewed the documentation together with engineering and this issue will be addressed in a future larger update. Closing this issue for now.
