### ISSUE TITLE
Q'n'A  -Does streaming segmentation “unqualification” also happen in real time?

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#195]
Hey team, 
about the following statement:
"For most instances, streaming segmentation unqualification happens in real-time. However, streaming segments that use segments of segments do not unqualify in real-time, instead unqualifying after 24 hours."

Question: a part the mentioned segments of segments, are there other cases ("most instances") where the unqualification does not happen in real-time?

Issue in ./help/segmentation/api/streaming-segmentation.md
Ref https://experienceleague.adobe.com/docs/experience-platform/segmentation/api/streaming-segmentation.html?lang=en

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-151241.

**Comment by vfalon** [comment]
We've reviewed the documentation and the statement is correct. There are no other exceptions. Closing this issue.
