### ISSUE TITLE
Invalid Documentation

### ISSUE THREAD

**Issue by shagreel** [AdobeDocs/experience-platform.en#199]
Issue in ./help/query-service/use-cases/activity-analysis-with-adobe-target.md

The Target data no longer flows into the platform in this fashion. This document should be removed.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-151242.

**Comment by vfalon** [comment]
We've reviewed the documentation and removed the outdated information. Closing this ticket.
