### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lucky-committ** [AdobeDocs/experience-platform.en#2]
Issue in ./help/tags/ui/managing-resources/rules.md

Re: "Enabled
If enabled, when an event is triggered at runtime, the rule’s conditions and actions are added to a processing queue–based on the order you have defined–and processed one at a time on a FIFO basis. The tag waits for the completion of the component before moving onto the next one."

Does this apply within rule or also outside of the rule itself... for example:
Rule 1, window load, order 49
Rule 2, window load, order 50

Does rule 1 _complete_ before rule 2 or just _start_  before rule 2?

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-113154.

**Comment by vgiurgiu** [comment]
@lucky-committ - note that rules themselves execute in sequence, regardless of how their rule components are sequenced. Rule 1 will complete before Rule 2 starts.

The documentation has now been updated. Please read:

- https://experienceleague.adobe.com/docs/experience-platform/tags/ui/rules.html?lang=en#rule-ordering
- https://experienceleague.adobe.com/docs/experience-platform/tags/ui/rules.html?lang=en#sequencing

If you find additional updates that are required, please open a new issue.
