### ISSUE TITLE
CONTAINER_ID global and tenant options

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#20]
For the CONTAINER_ID setting, are the possible values literally "global" and "tenant"? Or does the tenant need to refer to the actual tenant of the org (i.e., be the same value used as the TENANT_ID variable)? Could this be made clearer in the doc?

Issue in ./help/xdm/api/getting-started.md

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-63661

**Comment by pnolan89** [comment]
Concrete examples for each container have been added to the appropriate sections for further clarification: https://docs.adobe.com/content/help/en/experience-platform/xdm/api/getting-started.html#container
