### ISSUE TITLE
Update Release notes for Adobe Analytics Extension v.19.0

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/experience-platform.en#20]
The release notes are out of date. They haven't been updated since November 29, 2021 (Adobe Analytics Extension 1.8.8).

The current recommended version is v.1.9.0.

It is very helpful to know what has changed in any given version of an Adobe Extension before deploying it to production, so up to date release notes are quite important.

Issue in ./help/tags/extensions/web/analytics/release-notes.md

REF: https://experienceleague.adobe.com/docs/experience-platform/tags/extensions/adobe/analytics/release-notes.html?lang=en

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-116544.

**Comment by Brontojoris** [comment]
Any update on this issue?

**Comment by vfalon** [comment]
Hi @Brontojoris . The team is still working on updating this page with missing information. I'll update the status here when it's ready.

**Comment by vfalon** [comment]
The documentation has now been updated. Closing this issue.

**Comment by Brontojoris** [comment]
Thanks Vlad!
