### ISSUE TITLE
Doc mentions field which is no longer there

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#205]
Table in the "Set up a datastream" contains the following:

Streaming Inlet	A valid streaming connection for Experience Platform. See the tutorial on [creating a streaming connection](https://experienceleague.adobe.com/docs/experience-platform/ingestion/tutorials/create-streaming-connection-ui.html?lang=en) if you do not have an existing streaming inlet.

However, the streaming inlet field has not been part of the configuration for a long time and is not pictured in the screenshot.
Issue in ./help/landing/governance-privacy-security/consent/sdk.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-153904.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the necessary update. Closing this issue.
