### ISSUE TITLE
Error in the code of the section How to track events>Using Web SDK>Example 2

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#206]
Issue in ./help/edge/personalization/adobe-target/web-sdk-atjs-comparison.md

Section "How to track events>Using Web SDK>Example 2>code":
`for (var j = 0; j < proposition.items; j++) {`

This statement is wrong and the j won't cycle, as proposition.items is not a number.
Please replace with the following:
`for (var j = 0; j < proposition.items.length; j++) {`

Alberto

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-153905.

**Comment by vfalon** [comment]
We've updated the documentation with the correct code sample. Closing this issue.
