### ISSUE TITLE
It would be nice for this documentation to reference API authentication and tutorials documentation.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#209]
Issue in ./help/profile/api/entities.md

https://experienceleague.adobe.com/docs/experience-platform/profile/api/entities.html?lang=en

When providing information on APIs that can be leveraged it would be good to reference the API authentication documentation so users know how to get started with the APIs.

Here is the authentication information - https://experienceleague.adobe.com/docs/experience-platform/landing/platform-apis/api-authentication.html?lang=en#jwt

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-156783.

**Comment by vfalon** [comment]
Hey @nhecht, the Entities page (https://experienceleague.adobe.com/docs/experience-platform/profile/api/entities.html?lang=en) already links out to API getting started guide (https://experienceleague.adobe.com/docs/experience-platform/profile/api/getting-started.html?lang=en) where all the authentication information is provided.

Closing this issue.
