### ISSUE TITLE
Relationship tutorial suggestion.

### ISSUE THREAD

**Issue by woolleyadobe** [AdobeDocs/experience-platform.en#21]
Issue in help/xdm/tutorials/relationship-ui.md

Very confusing have hotelId in the ECID namespace. I think adds unnecessary complexity to this tutorial. Recommend creating a new hoteID namespace and taking new screenshots.

**Comment by pnolan89** [comment]
Screens and content have been updated to show the new namespace example: https://docs.adobe.com/content/help/en/experience-platform/xdm/tutorials/relationship-ui.html
