### ISSUE TITLE
Add default merge policy enable to Edge

### ISSUE THREAD

**Issue by pdimarco** [AdobeDocs/experience-platform.en#21]
Issue in ./help/destinations/ui/activate-profile-request-destinations.md

As i configured Target destination and activated my segment from AEP, the document indicates use of the default merge policy. However, you need to make sure your default merge policy is set Active on the edge. Otherwise you receive an error when activating the segment

![image](https://user-images.githubusercontent.com/65278/155761653-21a38bc6-4448-4be0-a5a7-c60fddbacfe4.png)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-116676.

**Comment by vfalon** [comment]
Documentation was updated. Closing the issue.
