### ISSUE TITLE
Note about data prep and data filtering

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#214]
Issue in ./help/sources/tutorials/ui/create/adobe-applications/analytics.md

We should add some clarifying notes:

- Filtering applies only to data going to profile, not data lake.
- ADC does not backfill data into profile.
- If the customer adds DataPrep during initial setup of the ADC Flow, it will be applied to the automatic 13-month backfill as well. 
- DataPrep is applied to both streaming and batch ingestion paths.  If an existing DataPrep configuration is modified, those changes will start impacting new incoming data across both of those ingestion pathways.  It will not, however, adjust any data which has already been received into AEP (streaming or batch).

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-159780.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly: https://experienceleague.adobe.com/docs/experience-platform/sources/ui-tutorials/create/adobe-applications/analytics.html?lang=en#filtering-for-profile. Closing this issue.
