### ISSUE TITLE
identity delete guidance

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#216]
Issue in ./help/hygiene/api/workorder.md

"If you are specifying a single dataset, the dataset’s associated Experience Data Model (XDM) schema must have a primary identity defined."

Does this mean the identity must not be in the identity map field? 
What if the dataset uses identity map and therefore does not have a primary ID set at the schema, but rather the primary ID is set in the identity map.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-160718.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the necessary updates. Closing this issue.
