### ISSUE TITLE
Put vs Get

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#217]
Issue in ./help/hygiene/api/workorder.md

This describes a PUT request, but then the example lower shows a GET request.

https://experienceleague.adobe.com/docs/experience-platform/hygiene/api/workorder.html?lang=en#:~:text=You%20can%20update%20the%20displayName%20and%20description%20for%20a%20record%20delete%20by%20making%20a%20PUT%20request.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-160719.

**Comment by vfalon** [comment]
We've reviewed and updated the documentation accordingly. Closing this issue.
