### ISSUE TITLE
Guardrails for # of requests that can be submitted in a single request

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#218]
Issue in ./help/hygiene/api/workorder.md

What is the maximum # of identities that should be submitted in a single request?

https://experienceleague.adobe.com/docs/experience-platform/hygiene/api/workorder.html?lang=en#:~:text=The%20following%20request%20deletes%20three%20identities%20from%20a%20specific%20dataset.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-160720.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly. Updates are live at
https://experienceleague.adobe.com/docs/experience-platform/data-lifecycle/ui/record-delete.html?lang=en#submit 
and https://experienceleague.adobe.com/docs/experience-platform/data-lifecycle/api/workorder.html?lang=en#create
