### ISSUE TITLE
Wrong parameters name suggested respect to corresponding XDM items 

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#220]
Good day.
The [article](https://experienceleague.adobe.com/docs/experience-platform/edge-network-server-api/personalization/personalization-target.html?lang=en#custom-parameters-example) states the following XDM structure:

```
"xdm":{
   "marketing":{
      "campaignGroup":"winter22",
      "campaignName":"homeOwnerPromo22",
      "trackingCode":"hop22"
   }
}
```
shall make available the following Target parameters (in the audience builder):

```
    xdm.marketing.campaignGroup
    xdm.marketing.campaignName
    xdm.marketing.trackingCode
```

That's not actually true. In fact the following parameters shall be available instead:

```
    marketing.campaignGroup
    marketing.campaignName
    marketing.trackingCode
```

Hence the question: given that XDM structure for correct

- It is expected the xdm. rooted parameters to be available in the Target audience builder (in this case the product is not working as expected)
- OR it is expected the marketing. rooted parameters to be available in the Target audience builder (in this case the documentation need to be fixed)?

Issue in ./help/server-api/personalization-target.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-160723.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it with the correct values, as reflected by the Target UI. Closing this issue.
