### ISSUE TITLE
Add guidance on the entity delete API

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#222]
Issue in ./help/profile/api/entities.md

We should add documentation guidance on the entity delete API, its use cases, guardrails, and considerations.
https://developer.adobe.com/experience-platform-apis/references/profile/#tag/Entities/operation/deleteEntity

For example does the merge policy result in all related profiles being deleted along with the requested profile.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-160724.

**Comment by vfalon** [comment]
This update is already being tracked in PLAT-152767. Closing this issue.
