### ISSUE TITLE
Product description says 3 merge policies but this doc says 5 merge policies.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#223]
Issue in ./help/profile/merge-policies/overview.md

If you look in the product description it says 3 merge policies are allowed. 
https://helpx.adobe.com/legal/product-descriptions/real-time-customer-data-platform.html#:~:text=Profile%20Merge%20Policies.%C2%A0%20Customer%20may%20use%20up%20to%203%20concurrent%20Profile%20Merge%20Policies%2C%20including%20any%20system%20Profile%20Merge%20Policies.

But this doc says 5 are allowed.
https://experienceleague.adobe.com/docs/experience-platform/profile/merge-policies/overview.html?lang=en#:~:text=a%20maximum%20of-,five%20merge,-policies%20allowed%20per

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-161243.

**Comment by vfalon** [comment]
The helpx page has been updated to reflect the correct number of merge policies (5). Closing this issue.
