### ISSUE TITLE
Update the Postman url

### ISSUE THREAD

**Issue by ch264** [AdobeDocs/experience-platform.en#23]
Hi there, 

the Postman URL has changed from  www.getpostman.com to www.postman.com. 

I have created a PR: https://github.com/AdobeDocs/experience-platform.en/pull/14

**Comment by djwendo** [comment]
Thank you for reporting this. We are tracking an internal update to ensure the changes are persisted in our public repo: https://jira.corp.adobe.com/browse/PLAT-69713

**Comment by pnolan89** [comment]
Outdated links have been updated: 

- https://docs.adobe.com/content/help/en/experience-platform/tutorials/authentication.html
- https://docs.adobe.com/content/help/en/experience-platform/data-science-workspace/authoring/feature-pipeline.html
