### ISSUE TITLE
Update Steps to Change Language Settings

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/experience-platform.en#231]
Issue in ./help/landing/browser-language-support.md

The steps to change user language no longer represent the current UI.

**Old Steps:**

To change your language:

1. Select the current language in the footer of the Experience Platform user interface.
2. In your profile settings, select Change Region.
3. Select your region.

**New Steps:**

To change your language:

1. Click 'ctrl + i' to bring up the Account Info menu _(is this shortcut different for Apple machines?)_
2. Navigate to Preferred languages
3. Select your primary and secondary language preferences
4. Save and close

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-163337.

**Comment by vfalon** [comment]
Docs updated. Closing this issue.
