### ISSUE TITLE
How to override the configs via Mobile SDK and Edge Network Server API?

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#232]
Issue in ./help/datastreams/overrides.md

Hi,
Datastreams are shared by Web SDK, Mobile SDK, and Edge Network Server API. This doc explains to add the configs to the datastream and how to "Send the overrides to the Edge Network via the Web SDK" but where is the equivalent "Send the overrides" content for Mobile SDK and Edge Network Server API? If it exists elsewhere can you add links from this page? If it doesn't exist, can content be added here?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-162780.

**Comment by vfalon** [comment]
We've updated the overrides documentation to reflect support for Web SDK only. Closing this issue.
