### ISSUE TITLE
Broken link: Adobe Experience Platform Mobile SDK: An extension to the v5 mobile SDK

### ISSUE THREAD

**Issue by AntonioNoack** [AdobeDocs/experience-platform.en#233]
Issue in ./help/edge/home.md

In this section:
![image](https://github.com/AdobeDocs/experience-platform.en/assets/20659579/4a89a63c-03bd-4f52-8587-5d1bcf957119)
the second link is broken. It reports a 404 Not Found page:
![image](https://github.com/AdobeDocs/experience-platform.en/assets/20659579/133dacdf-48b8-4bc6-bfb4-1c6ed273a98e)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-163026.

**Comment by vfalon** [comment]
The link is now fixed. Closing this issue.
