### ISSUE TITLE
Custom Personalization - does not require websdk/mobilesdk as noted

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#234]
Issue in ./help/destinations/catalog/personalization/custom-personalization.md

The doc states 
"This integration is powered by the [Adobe Experience Platform Web SDK](https://experienceleague.adobe.com/docs/experience-platform/edge/home.html?lang=en) or the [Adobe Experience Platform Mobile SDK](https://aep-sdks.gitbook.io/docs/). You must be using one of these SDKs to use this destination."

When in actuality this feature can be used by the Edge Server API as well, without requiring the Web or Mobile SDK.

In addition it would be helpful if this guide differentiated guidance on how this is deployed on Web/Mobile SDK vs. deployed on the Edge Server API.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-163338.
