### ISSUE TITLE
Picture Change in Product String doc

### ISSUE THREAD

**Issue by kikiisong** [AdobeDocs/experience-platform.en#239]
Issue in ./help/tags/extensions/client/product-string/overview.md

The picture used for **Action Sequence** seems incorrect (it's the same as in **Price Type**)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-165825.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated the image. Closing this issue.
