### ISSUE TITLE
What happens when the same identity exists across multiple datasets for None and private merge policy.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#24]
Issue in ./help/profile/merge-policies/overview.md

Suppose there are 2 datasets 
each with email set as the primary id namespace.
This would result in two profile fragments - 1 for each dataset.

What would happen with these 2 fragments - will they merge or not for the "none" merge policy?

Providing clarification in the documentation on this scenario would be helpful.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-117165.

**Comment by vfalon** [comment]
@nhecht the documentation team has investigated this scenario and the answer is that the profiles would **not** be merged, as mentioned in the docs:

"None: When this option is selected, IDs will not be stitched together. When segmentation occurs, identities that may belong to the same person will not be stitched together and segmentation will only consider the attributes attached to each individual ID when determining if a customer qualifies for segment membership."

Closing this issue.
