### ISSUE TITLE
Require API's documentation for RTCDP facebook Destination

### ISSUE THREAD

**Issue by richa-adobe** [AdobeDocs/experience-platform.en#24]
Issue in help/rtcdp/destinations/facebook-destination.md.

Please provide API documentation for RTCDP facebook destination. It would be great to have sample postman collection too.

Please also update, what all would be required from FB business account side also.

**Comment by vgiurgiu** [comment]
Thanks for creating this issue, @richa-adobe . We're tracking progress for this update internally in https://jira.corp.adobe.com/browse/PLAT-67493

To answer your question about what is needed from the Facebook business account side, refer to this section:
https://docs.adobe.com/content/help/en/experience-platform/rtcdp/destinations/destinations-cat/social-destinations/facebook-destination.html#facebook-account-prerequisites

**Comment by vgiurgiu** [comment]
Providing an update here. The work to create an API tutorial for Facebook is currently blocked. We cannot provide an estimate as to when the documentation will be available.

**Comment by vgiurgiu** [comment]
@richa-adobe  - we are not planning to support API functionality for connecting to the Facebook destination. Please use the UI functionality to connect to Facebook and activate segments:
https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/social/facebook.html

Closing this issue.
