### ISSUE TITLE
Inaccurate product/capability hierarchy in new use case guide

### ISSUE THREAD

**Issue by pnolan89** [AdobeDocs/experience-platform.en#240]
https://github.com/AdobeDocs/experience-platform.en/blob/02ce6daaa160896ff9757792f4ad55c499f1a879/help/rtcdp/use-case-guides/intelligent-re-engagement/intelligent-re-engagement.md?plain=1#L25-L34

The structure of this list implies everything is an RTCDP feature, including AJO. It should be more like the following:

- RTCDP
  - Schemas
  - Profiles
  - Datasets
  - Audiences
  - Destinations
- AJO
  - Event or Audience Trigger
  - Audiences / Events
  - Journey Actions

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-165827.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the required updates. Closing the issue.
