### ISSUE TITLE
Illegible journey diagrams in new use case doc

### ISSUE THREAD

**Issue by pnolan89** [AdobeDocs/experience-platform.en#241]
https://github.com/AdobeDocs/experience-platform.en/blob/02ce6daaa160896ff9757792f4ad55c499f1a879/help/rtcdp/use-case-guides/intelligent-re-engagement/intelligent-re-engagement.md?plain=1#L450C174-L450C174

When I click on one of the journey maps in this doc, it's not zoomed in enough for me to parse without some serious difficulty, and the UI refuses to let me zoom in further even with the manual browser zoom.

Interestingly the PNG file in the repo seems to have more than enough resolution to see the fine details, so it look like something is wrong with how this is rendering within the tabs feature.

https://github.com/AdobeDocs/experience-platform.en/assets/44183179/65a68ebb-c3ac-4e64-bf1c-5d7cc68f33ac

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-165828.

**Comment by vfalon** [comment]
Closing this issue, since it's not a documentation problem. Tracking internally in UGP-9508.

**Comment by pnolan89** [comment]
Gotcha, makes sense this is an issue for the ExL team. Thanks @vfalon 😃
