### ISSUE TITLE
Is not geographic information such as geo location, zip code, ip address, domain also automatically collected?

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#242]
Issue in ./help/edge/data-collection/automatic-information.md

Is not geographic information such as geo location, zip code, ip address, domain also automatically collected?

I did not see any reference to geographic or IP address information on this page.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-165831.

**Comment by vfalon** [comment]
The recent Web SDK docs revamp covered this topic in a dedicated page for the context property: https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/commands/configure/context.

Closing this issue.
