### ISSUE TITLE
Possible typo in documentation

### ISSUE THREAD

**Issue by Msteimel** [AdobeDocs/experience-platform.en#243]
Issue in ./help/tags/ui/managing-resources/data-elements.md

`If you use a data collector object as party of your data layer`

I assume it's a typo and `party` should be `part`

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-165832.

**Comment by vfalon** [comment]
We've updated the documentation to remove the typo. Closing this issue.
