### ISSUE TITLE
Possible internal comment published live

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#245]
Good day team.
The section "Add the third-party data governance label to all fields in the schema" feature the following comment in bracket:
"add link to docs by Jordan".

That sounds like an internal comment. Mind to check it out?
![immagine](https://github.com/AdobeDocs/experience-platform.en/assets/100088147/2719d5e6-d5be-458d-b93e-762ba215ec75)

Issue in ./help/rtcdp/partner-data/prospecting.md

**Comment by vfalon** [comment]
Thanks for reporting this. The comment was addressed. Closing this issue.
