### ISSUE TITLE
Why does AJO use an RSA public key for PGP instead of a PGP public key?

### ISSUE THREAD

**Issue by contentfree** [AdobeDocs/experience-platform.en#249]
Issue in ./help/destinations/catalog/cloud-storage/amazon-s3.md

Documentation states:
Encryption key: Optionally, you can attach your RSA-formatted public key to add encryption to your exported files. View an example of a correctly formatted encryption key in the image below.

However, the field is PGP/GPG encryption key. Using a PGP public key appears to lead to a failure when sending the file to the destination (though the .gpg file _is_ uploaded to S3; it's zero bytes).

A GPG public key starts with `-----BEGIN PGP PUBLIC KEY BLOCK`

The error AJO reports in the run is "This public key (0x…) is not suitable for encryption. Please verify that you have sufficient storage space in the destination". This is a known-good GPG encryption key.

**Comment by vfalon** [comment]
Hi @contentfree, and thanks for raising this. Trying to understand whether this is a configuration issue or a documentation issue.

The destination you mentioned supports PGP/GPG encryption keys **in RSA format**. I understand you are using a GPG encryption key. Is that key using the RSA algorithm, or a different one?

**Comment by contentfree** [comment]
My GPG key is a DSA key. Also the format of the public key from GPG Suite,
for example, starts -----BEGIN PGP PUBLIC KEY BLOCK----- and not -----BEGIN
PUBLIC KEY-----

I believe converting DSA to RSA is impossible. GPG supports my key fine and
has for very many years.

Dave

**Comment by vfalon** [comment]
@contentfree , as mentioned in the documentation, the destinations only support RSA keys. DSA-formatted keys are not supported. You need an RSA key to connect to the destination. Closing this issue, since the documentation is correct. We'll also update the sample to include the full starting block.
