### ISSUE TITLE
Need to Set a Max version for psql

### ISSUE THREAD

**Issue by M777A2** [AdobeDocs/experience-platform.en#25]
Issue in help/query-service/clients/psql.md

Using these instructions I installed Postgres 12.3 and was unable to connect to AEP servers.

After rolling back my Postgres version to 10.14 I was able to connect as intended.

The Docs should specify which versions of the Postgres client are compatible with Query Service.

---
Contact at zthe@adobe.com

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-69712

**Comment by djwendo** [comment]
The documentation has now been updated to clarify connection instructions.
https://experienceleague.adobe.com/docs/experience-platform/query/clients/psql.html?lang=en#connect-psql-and-query-service
