### ISSUE TITLE
EE guardrail - 5,000 EE per profile

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#25]
Issue in ./help/profile/guardrails.md

There is a guardrail of 5,000 EE per profile, which is not listed here.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-116679.

**Comment by vfalon** [comment]
@nhecht this seems to be a duplicate of https://github.com/AdobeDocs/experience-platform.en/issues/22. We're tracking it  internally in PLAT-116679. Closing this issue.
