### ISSUE TITLE
AEP event forwarding links to AAM documentation

### ISSUE THREAD

**Issue by seandickson109** [AdobeDocs/experience-platform.en#252]
Issue in ./help/tags/ui/event-forwarding/getting-started.md

The "server to server API" link at the top of this page points to the Audience Manager server to server documentation. It should point to the Edge Network API documentation.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-169448.

**Comment by vfalon** [comment]
We've updated the documentation to link tot he correct page. Closing this issue.
