### ISSUE TITLE
AEP Privacy Service - Documentation: Suggestion for Clarification

### ISSUE THREAD

**Issue by hilpdesk** [AdobeDocs/experience-platform.en#253]
We noticed that the documentation on the AEP Privacy Service UI [1] mentions the requirement to have System Administrator rights for the Privacy UI, which is in conflict with the documentation on permissions [2].
 
[1] https://experienceleague.adobe.com/docs/experience-platform/privacy/ui/overview.html?lang=en
[2] https://experienceleague.adobe.com/docs/experience-platform/privacy/permissions.html?lang=en
 
The introduction in [2] emphasizes that Adobe introduced the granular permissions approach exactly to eliminate that previous System Admin requirement still indicated in [1] – hence I believe the latter documentation is confusing here.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-169449.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the necessary updates. Closing this issue.
