### ISSUE TITLE
Need to add edge api as 

### ISSUE THREAD

**Issue by seandickson109** [AdobeDocs/experience-platform.en#254]
Issue in ./help/tags/ui/event-forwarding/getting-started.md

Under prerequisites, one option needs to be added to the third bullet: Edge Network Server API

"Prerequisites
- Adobe Real-Time CDP Connections, Prime, or Ultimate (Contact your Adobe account team for pricing)
- Event forwarding in Adobe Experience Platform
- Adobe Experience Platform Web or Mobile SDK, configured to send data to Edge Network
- Map data to Experience Data Model (XDM) (This mapping can be done using tags)"

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-169450.

**Comment by vfalon** [comment]
We've updated the documentation to include the Edge Network Server API.
