### ISSUE TITLE
Streaming seg does not support Patch updates

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#255]
Issue in ./help/segmentation/ui/streaming-segmentation.md

"Streaming segmentation works on all data that was ingested using a streaming source. Data ingested using a batch-based source will be evaluated nightly, even if it qualifies for streaming segmentation."

We have discovered that streaming segmentation does not currently support PATCH updates on the profile. So it would be helpful to have this information added to the documentation.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-169451.

**Comment by vfalon** [comment]
Closing this issue based on documentation team's assessment.
