### ISSUE TITLE
Create a Privacy Job section -- minor terminology correction

### ISSUE THREAD

**Issue by sartsche** [AdobeDocs/experience-platform.en#256]
Minor issue found in [privacy-jobs.md ](https://github.com/AdobeDocs/experience-platform.en/blob/main/help/privacy-service/api/privacy-jobs.md) under Create a privacy job section. 

What's written: 
"users (Required): An array containing a collection of at least one user whose information you would like to access or delete. A maximum of 1000 user IDs can be provided in a single request."

When describing the maximum count per single request-- this should actually be users not user IDs. 

What this should say:
"users (Required): An array containing a collection of at least one user whose information you would like to access or delete. A maximum of 1000 _users_ can be provided in a single request."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-170166.

**Comment by vfalon** [comment]
The docs team has reviewed and updated the page accordingly. Closing this issue.
