### ISSUE TITLE
Discrepency in AEP UI access for non AEP licensed customers

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-platform.en#26]
Issue in ./help/edge/web-sdk-faq.md

The documentation state

**Do customers need to buy Adobe Experience Platform to use the Web SDK?

No. Any Adobe Digital Experience customer can use it. Totally free. Any customer wanting to use the Web SDK will be given access to create schemas and datasets in the Adobe Experience Platform UI.**

Given that customers without the AEP license can use Web SDK and leverage ID Sync for "Visitor Attributes", they should also have access to the UI to create Identity namespace.

The document should explicitly call this out. 

https://experienceleague.adobe.com/docs/experience-platform/edge/web-sdk-faq.html?lang=en#do-customers-need-to-buy-adobe-experience-platform-to-use-the-web-sdk%3F

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-117510.

**Comment by vfalon** [comment]
The documentation was updated with the suggested information.
