### ISSUE TITLE
Requires B2B

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#260]
Issue in ./help/xdm/data-types/external-source-system-audit-attributes.md

Is this still accurate? "This data type is only available for organizations that have access to the B2B edition of Adobe Real-Time Customer Data Platform."

**Comment by dwright-adobe** [comment]
Also, this page could use some more context about why you would want to use this field group.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-170167.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it accordingly.
