### ISSUE TITLE
Add documentation for datastream config override support via AEP Mobile SDK

### ISSUE THREAD

**Issue by addb** [AdobeDocs/experience-platform.en#265]
AEP Mobile SDK is adding support for datastream ID override and datastream config override, so would like this page to include some details for that.

Mobile docs PR for reference:
https://github.com/AdobeDocs/aep-mobile-sdkdocs/pull/427

**Comment by vfalon** [comment]
Closing this issue as it was tracked and resolved in PLAT-171257.
