### ISSUE TITLE
Please add Apply Response action documentation

### ISSUE THREAD

**Issue by vadymus** [AdobeDocs/experience-platform.en#268]
Issue in ./help/tags/extensions/client/web-sdk/action-types.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-172023.

**Comment by vfalon** [comment]
Closing this issue as it will be covered in PLAT-140473, along with other similar update.
