### ISSUE TITLE
Missing details about Import Audience

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#270]
Good day team.
The audience import has been [released in July'23](https://experienceleague.adobe.com/docs/experience-platform/release-notes/2023/july-2023.html?lang=en#segmentation). [This tutorial ](https://experienceleague.adobe.com/docs/platform-learn/tutorials/audiences/upload-audiences.html?lang=en )refers the Segment Builder UI page for more information about the audience upload. But currently the [Segment Builder UI ](https://experienceleague.adobe.com/docs/experience-platform/segmentation/ui/segment-builder.html?lang=en )page does not report any details about the audience import.
Specifically about:

- the file format (fields separator, escape sequences, compression, etc) 
- the allowed attributes data types and format
- the audience evaluation method and duration
- guardrails about file size, number of rows, etc

Could you please include such details?

Thanks,
Alberto

Issue in ./help/segmentation/ui/segment-builder.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-172025.

**Comment by vfalon** [comment]
We've updated the docs with more detailed information. Closing this ticket.
