### ISSUE TITLE
Page readable through the mktossl.com domain.

### ISSUE THREAD

**Issue by tarcizio** [AdobeDocs/experience-platform.en#277]
Issue in ./help/landing/license-usage-and-guardrails/data-management-best-practices.md

I Googled "AEP profile richness" and the page 
https://docs.mktossl.com/docs/experience-platform/landing/license/data-management-best-practices.html?lang=en#license-usage-dashboard
was returned.  The domain on the page is mktossl.com and not adobe.com this is probably not a desired result.

The same page can be found by navigating down to it and keeps the appropriate domain.
https://experienceleague.adobe.com/docs/experience-platform/landing/license/data-management-best-practices.html?lang=en#license-usage-dashboard

**Comment by vfalon** [comment]
Thank you for reporting this. We're tracking it internally in UGP-8204.

**Comment by vfalon** [comment]
The mktossl.com domain has been removed from search results. Direct URLs still work, but will be removed in the future. Closing this issue.
