### ISSUE TITLE
Documentation change for String function 'split(INPUT, SEPARATOR)'

### ISSUE THREAD

**Issue by delacues** [AdobeDocs/experience-platform.en#279]
Issue in ./help/data-prep/functions.md

Here is the proposesd change for String function '`split(INPUT, SEPARATOR)`':

https://experienceleague.adobe.com/docs/experience-platform/data-prep/functions.html?lang=en#string

The proposal came from customer's support ticket E-001084389. This is the context:

_Using the "split" function and choosing the relevant array position to map to a specific schema field, should be able to handle "empty" positions in the string. Just like using the substring feature in Customer Journey Analytics, or in the Classification Rule Builder in Adobe Analytics._

_However empty positions in the string are merely discarded, rather than added as "null" array positions. This has profound consequences for strings not fully populated._

_That being said, then perhaps you should update the documentation, as the behaviour deviates significantly compared to other languages; both Python and JavaScript, for example, will treat empty indexes as empty strings, rather than leave them out completely. I foresee other AEP customers being affected by this design choice as well._

_As a workaround we will instead be using the "explode" function, because adding placeholder text in empty positions would introduce issues in both Adobe Analytics, CJA, and RT-CDP._

Current text:

_Splits an input string on a separator. The following separator needs to be escaped with \: \. If you include multiple delimiters, the string will split on any of the delimiters present in the string._

Proposed text:

_Splits an input string on a separator. The following separator needs to be escaped with \: \. If you include multiple delimiters, the string will split on any of the delimiters present in the string._

_Note that this function only returns non-null indexes from the string, regardless of the presence of the separator. If all indexes, including nulls, are required in the resulting array, use the "explode" function instead._

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-176374.

**Comment by vfalon** [comment]
We've reviewed and updated the documentation. Closing this issue.
