### ISSUE TITLE
Examples point to older code

### ISSUE THREAD

**Issue by jklockow** [AdobeDocs/experience-platform.en#28]
Issue in help/edge/fundamentals/installing-the-sdk.md

The URL examples and code examples on this page point to version 1.0.0 of the Web SDK. The latest version is now version 2.1.0.  Can we ad some language about where the version is indicated and how to find out what the latest version is?

For example, this URL points to version 1.0.0: https://cdn1.adoberesources.net/alloy/1.0.0/alloy.min.js.
Just changing the path points to a newer version: https://cdn1.adoberesources.net/alloy/2.1.0/alloy.min.js

Code block is similar.

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-69707

**Comment by Joshua-McGee** [comment]
This issue has been resolved.
