### ISSUE TITLE
The link to the list of IAB vendors need to be updated

### ISSUE THREAD

**Issue by lesutton** [AdobeDocs/experience-platform.en#282]
Issue in ./help/landing/governance-privacy-security/consent/iab/overview.md

https://iabeurope.eu/vendor-list-tcf/

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-176375.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated the link. Closing this issue.
