### ISSUE TITLE
It's not clear how to specify multiple values in the Exclusion rules

### ISSUE THREAD

**Issue by albyangeli** [AdobeDocs/experience-platform.en#286]
Issue in ./help/segmentation/ui/audience-composition.md

When you select "Exclude using attribute"a field called "Excluded values" appears. In the documentation is not specified how to list multiple values.

![image](https://github.com/AdobeDocs/experience-platform.en/assets/7655387/b0e64f52-8732-4af9-8598-e6f11957ca61)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-178614.

**Comment by vfalon** [comment]
We've reviewed the documentation and added details around excluding values. Closing this issue.
