### ISSUE TITLE
Missing information about Audience Composition

### ISSUE THREAD

**Issue by albyangeli** [AdobeDocs/experience-platform.en#287]
Issue in ./help/profile/computed-attributes/ui.md

In the section "Using Computed Attributes" is not specified if Computed Attributes can be used in Audience Composition. Can you please add this information?

Thanks

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-178615.

**Comment by vfalon** [comment]
We've reviewed the documentation and added a note in this page https://experienceleague.adobe.com/docs/experience-platform/profile/computed-attributes/ui.html?lang=en related to computed attributes support. Closing this issue.
