### ISSUE TITLE
Wrong term

### ISSUE THREAD

**Issue by ericthibeault-adobe** [AdobeDocs/experience-platform.en#288]
Issue in ./help/edge/fundamentals/executing-commands.md

function(result) {
    // The command succeeded.
    // "value" is whatever the command returned

I think in this example, the term "value" should be replaced with "result"

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-178616.

**Comment by vfalon** [comment]
We've updated the documentation with the correct term. Closing this issue.
