### ISSUE TITLE
Streaming segment guardrail

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#29]
Issue in ./help/segmentation/ui/streaming-segmentation.md

There was input from the engineering team Sekar Krishnamurthy and Stephen Own that the below may not be supported in streaming segmentation
There is a concern on how the streaming segmentation could scale to this. 
Recommend reviewing with the product team whether or not we should allow query of multiple events for streaming segmentation and adjusting accordingly.

Multiple events with a profile attribute | Any segment definition that refers to multiple events within the last 24 hours and (optionally) has one or more profile attributes.
-- | --

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-118014.

**Comment by vgiurgiu** [comment]
Closing this issue. As per segmentation PM, the excerpt above is currently supported. More information in PLAT-118014.
