### ISSUE TITLE
What does 'active' lifecycle status mean in Audiences?

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/experience-platform.en#293]
Issue in ./help/segmentation/faq.md
Under the section: What do the different lifecycle states represent?
The table missed 'active' status.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-178618.

**Comment by vfalon** [comment]
We've reviewed the documentation and added details related to the Active status. Closing this issue.
