### ISSUE TITLE
Edge Segmentation

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#295]
Issue in ./help/datastreams/configure.md

Edge Segmentation section.

- We can add that it supports same page personalization for offer decisioning.
- We can add as well that it can be evaluated through the Edge API. It mentions the SDK but not the Edge API

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-178619.

**Comment by vfalon** [comment]
We've updated the documentation to include the suggested information. Closing this issue.
