### ISSUE TITLE
Link to Audience Manager connector tutorial leads to old tutorial page on Adobe.io

### ISSUE THREAD

**Issue by vgiurgiu** [AdobeDocs/experience-platform.en#3]
Issue in help/source-connectors/ui/adobe-applications/audience-manager.md

The hyperlink in the sentence below takes readers to the old tutorials page on Adobe.io. We should update the link to the new page on docs.adobe.com.

For instructions on creating a connection with Adobe Audience Manager using the Platform UI, see the Audience Manager connector tutorial .

**Comment by djwendo** [comment]
A fix has been merged and is in the activation queue. 👍
