### ISSUE TITLE
Inconsistency between public docs and XDM preferences schema

### ISSUE THREAD

**Issue by ancasuliman** [AdobeDocs/experience-platform.en#3]
Hello!

On the [_Consents and Preferences data type_](https://experienceleague.adobe.com/docs/experience-platform/xdm/data-types/consents.html?lang=en#adid) public documentation page, I observed that the `adID` field does not include the `idType` property, that is present within the [XDM Consent Preferences schema](https://github.com/adobe/xdm/blob/master/docs/reference/datatypes/consent/consent-preferences.schema.md#consent-for-privacy-personalization-and-marketing-preferences-example).

Can you please update the public documentation accordingly?

Thank you!

**Comment by vgiurgiu** [comment]
Hello! Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-113610.

**Comment by vgiurgiu** [comment]
The documentation has now been updated. 

The data type reference page has been updated to include info on the `adID.idType` field: https://experienceleague.adobe.com/docs/experience-platform/xdm/data-types/consents.html#adid
