### ISSUE TITLE
Adobe.io Developer API reference docs

### ISSUE THREAD

**Issue by tgiffin** [AdobeDocs/experience-platform.en#305]
Issue in ./help/hygiene/api/overview.md
This API does not seem to be listed in the API docs on https://developer.adobe.com/experience-platform-apis/ 
Are the API endpoints documented somewhere else? Or under a different API parent?  Is this API so new that it has not been added to the Developer's References yet?

I am sorry, also the Thumbs up and Thumbs down FEEDBACK dialog on Safari and Chrome for feedback do not work, so I had to use this report an issue

Thank you

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-181484.

**Comment by vfalon** [comment]
Docs are live at:
https://developer.adobe.com/experience-platform-apis/references/data-hygiene/ 

Closing this issue.
