### ISSUE TITLE
Mismatch in values

### ISSUE THREAD

**Issue by sammydude22** [AdobeDocs/experience-platform.en#306]
Issue in ./help/identity-service/guardrails.md

<img width="795" alt="Screenshot 2024-02-04 at 2 07 59 PM" src="https://github.com/AdobeDocs/experience-platform.en/assets/158799823/8ee93630-0229-45b2-8bac-7f6904fefbb4">

The value in the Limit field shows 20 while the Notes mentions Two.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-181485.

**Comment by vfalon** [comment]
We've reviewed the documentation and confirmed that it is correct. Values are supposed to be mismatched. **Limit** column explicitly describes the **maximum** and the notes column explicitly describes the **minimum**, hence the different values. Closing this issue.
