### ISSUE TITLE
Please provide sample app of the server side implementation github link 

### ISSUE THREAD

**Issue by manishadb** [AdobeDocs/experience-platform.en#309]
Issue in ./help/server-api/personalization-target.md

Please provide sample app of the server side implementation github link 
https://github.com/adobe/alloy-samples/tree/main/target

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-181488.

**Comment by vfalon** [comment]
We've reviewed the documentation and added the link to the server-side implementation app.
