### ISSUE TITLE
typo in JSON

### ISSUE THREAD

**Issue by jklockow** [AdobeDocs/experience-platform.en#31]
Issue in help/edge/solution-specific/analytics/link-tracking.md

"webPageDetailsr" had trailing "r". Should be just "webPageDetails"

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-69705

**Comment by Joshua-McGee** [comment]
Resolved the issue, documentation is live [here](https://docs.adobe.com/content/help/en/experience-platform/edge/solutions/analytics/link-tracking.html)
