### ISSUE TITLE
Add profile limit

### ISSUE THREAD

**Issue by cscrewvala** [AdobeDocs/experience-platform.en#313]
Issue in ./help/segmentation/ui/audience-composition.md

Change:
Additionally, you can limit the number of audiences returned by enabling the Add profile limit toggle.

To:
Additionally, you can limit the number of profiles returned by enabling the Add profile limit toggle.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-181493.

**Comment by vfalon** [comment]
We've reviewed the docs and updated the page accordingly. Closing this issue.
