### ISSUE TITLE
Github project 404

### ISSUE THREAD

**Issue by alexbishop010** [AdobeDocs/experience-platform.en#315]
Issue in ./help/edge/fundamentals/top-bottom-page-events.md

The link to the github project ends on a 404 page

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-181494.

**Comment by vfalon** [comment]
We're reviewed the documentation and fixed the link. Closing this issue.
