### ISSUE TITLE
Make "Active-on-edge" merge policy more prominent

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/experience-platform.en#319]
Issue in ./help/destinations/catalog/personalization/adobe-target-connection.md

Given that this Target destination is a pre-configured, "out-of-the-box" destination, the reader can easily mistake this guide as a self-contained, one-stop-shop for how to configure this destination. Customers see this as a "Target Destination" and not an "edge personalization" destination. As such, the requirement that only Audiences that use an Active-On-Edge Merge policy are allowed to be used with this Target Destination is not clearly called out. Yes, there is an "Activate audiences to this destination" section that contains a link to the documentation that does spell out that requirement. But again, it takes a few clicks to get there, assuming one even notices the linked documentation. 

I'd recommend a change to the "Supported audiences" section that clearly calls out this requirement much earlier in the documentation. I'd even recommend we merge  "Activate audiences to this destination" and the "Supported audiences" sections. 

In the Description column for the "Segmentation Service" row in the "Supported Audiences" section, we adjust the text to create two bullet points. One is the original text, and the other is some text I'd like to add:

- Audiences generated through the Experience Platform [Segmentation Service](https://experienceleague.adobe.com/docs/experience-platform/segmentation/home.html?lang=en). 
- Audiences used in this destination will need to use a merge policy with the "Active-on-Edge" toggle enabled. For more details, please read [Activate audiences to edge personalization destinations](https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-edge-personalization-destinations.html?lang=en). "

Then move the Important note currently in the "Activate audiences to this destination" section to the bottom of the "Supported Audiences" section, and you can remove the "Activate audiences to this destination" section altogether.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-184436.

**Comment by vfalon** [comment]
We've updated the Supported Audiences section to include the merge policy requirement. We won't modify the rest of the page, since it follows the standardized format for all destination pages. The note in the supported audiences section should be clear enough.
