### ISSUE TITLE
Incorrect spelling of Adobe - Spelt Adoube

### ISSUE THREAD

**Issue by Shweta-Ram** [AdobeDocs/experience-platform.en#321]
Issue in ./help/edge/personalization/web-in-app-messaging.md
<img width="638" alt="Screenshot 2024-02-23 083409" src="https://github.com/AdobeDocs/experience-platform.en/assets/98167543/68545c0f-17bb-4ef2-97ba-256553499753">

**Comment by vfalon** [comment]
Thank you for reporting this typo. We've fixed it, so we're closing this issue.
