### ISSUE TITLE
LastUpdatedDate was described as timestamp field for Profile ingestion, but its not present anymore in the documentation

### ISSUE THREAD

**Issue by xgarcia2023** [AdobeDocs/experience-platform.en#328]
Issue in ./help/xdm/data-types/external-source-system-audit-attributes.md

In previous version of this document, LastUpdatedDate was described as timestamp field for profile ingestion and its affecting the merge policy functionality

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-184437.

**Comment by vfalon** [comment]
The documentation was updated. Closing this issue.
