### ISSUE TITLE
tutorial feedback

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#33]
Issue in help/ingestion/quality/error-diagnostics.md

I'm having trouble following this tutorial. 
The first part covers some sort of error diagnostics, but then later on it introduces other error diagnostics. It's hard to know the difference of what is what.

This appears lower in the document, and then another sort of error diagnostic appears higher in the document, I'm totally lost.

Partial batch ingestion error types
Partial batch ingestion has three different error types when ingesting data:
Unreadable files
Invalid schemas or headers
Unparsable rows
Unreadable files
If the batch ingested has unreadable files, the batch's errors will be attached on the batch itself. More information on retrieving the failed batch can be found in the retrieving failed batches guide .
Invalid schemas or headers
If the batch ingested has an invalid schema or invalid headers, the batch's errors will be attached on the batch itself. More information on retrieving the failed batch can be found in the retrieving failed batches guide .
Unparsable rows
If the batch you ingested has unparsable rows, you can use the following request to view a list of files that contain errors.

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-71545

**Comment by djwendo** [comment]
The documentation has been updated and this Jira issue is marked as closed. If further updates are needed, please open a new issue or Jira ticket.
