### ISSUE TITLE
streaming support for upsert not supported

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#33]
Issue in ./help/profile/tutorials/add-profile-data.md

the doc refers to streaming support for upsert, but streaming is not currently supported.

"This can be done through batch or streaming ingestion and requires a Profile-enabled dataset configured with an upsert tag. For more information on how to configure a dataset for attribute updates, please refer to the tutorial for [enabling a dataset for Profile and upsert](https://experienceleague.adobe.com/docs/experience-platform/catalog/datasets/enable-upsert.html?lang=en)."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-118173.

**Comment by vfalon** [comment]
@nhecht the documentation team has verified this information, and the documentation is correct.

Upsert can be used for streaming, but users don't need to enable this at the dataset level. It depends on the type of message you pass along that determines whether its a patch or a put operation. Patch in streaming has been in a place for a very long time.

Closing this ticket.

**Comment by nhecht** [comment]
@vfalon  - understood streaming is supported. But I do not believe the method described in the article does support streaming upsert and I could not find anywhere in the docs that described how to format the payload for streaming upsert, is there are reference for that somewhere?
