### ISSUE TITLE
Instruction/message is not clear

### ISSUE THREAD

**Issue by DiptimanBadajena** [AdobeDocs/experience-platform.en#332]
Issue in ./help/segmentation/ui/lookalike-audiences.md

The following paragraph about Look-Alike audience seems to be repetitive:
> "By default, the modeling process for Look-alike audiences will exclude any field, dataset, or audience based on the enabled privacy policy for your organization. If the base audience has no contract labels, the modeling process will exclude any field, dataset, or audience based on the enabled privacy policy for your organization."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-189877.

**Comment by vfalon** [comment]
We've reviewed the documentation and clarified the statement. Closing this issue.
