### ISSUE TITLE
missing event type decisioning.propositionFetch

### ISSUE THREAD

**Issue by manishadb** [AdobeDocs/experience-platform.en#333]
Issue in ./help/xdm/classes/experienceevent.md

We don't have details about the event type **decisioning.propositionFetch** 
which is described at https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/use-cases/top-bottom-page-events

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-197238. Closing this issue since it's already tracked separately.
