### ISSUE TITLE
External audience in Audience Composition

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/experience-platform.en#334]
Issue in ./help/segmentation/ui/audience-composition.md

Hi, as far as I know External Audiences cannot be used in Audience Composition. If it's true, can you please mention in the documentation?

Thanks

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-189879.

**Comment by vfalon** [comment]
We've reviewed the documentation and added a clarifying section around external audiences. Closing this issue.
