### ISSUE TITLE
Description for `kndctr_orgid_consent_check` and `kndctr_orgid_consent` is not accurate

### ISSUE THREAD

**Issue by raresvla** [AdobeDocs/experience-platform.en#335]
Issue in ./help/web-sdk/faq.md

Description must be swapped, to read:

| Cookie | Description |
|--------|--------|
| kndctr_orgid_consent_check | This session-based cookie signals the server to look up the consent preferences server side. |
| kndctr_orgid_consent | This cookie stores the user’s consent preference for the website. |

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-188598.

**Comment by vfalon** [comment]
We've fixed the descriptions. Closing this issue.
