### ISSUE TITLE
Update sendEvent example

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#340]
Issue in ./help/web-sdk/commands/sendevent/overview.md
This isn't a good example of a sendEvent as documentUnloading: true and renderDecisions: true are incompatible settings in the same call:

```
alloy("sendEvent", {
  "data": dataObject,
  "documentUnloading": true,
  "edgeConfigOverrides": { "datastreamId": "0dada9f4-fa94-4c9c-8aaf-fdbac6c56287" },
  "renderDecisions": true,
  "type": "commerce.purchases",
  "xdm": adobeDataLayer.getState(reference)
});
```

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-189881.

**Comment by vfalon** [comment]
Updated the documentation & closing this issue.
