### ISSUE TITLE
Adobe Experience platform MSSQL connector not working

### ISSUE THREAD

**Issue by shrivabee** [AdobeDocs/experience-platform.en#341]
MS SQL connector has a specified connection string format which doesnt seem to be working and there is not even a sample string provided in the documentation.

Can someone please help if they have setup this connection in the past?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-189882.

**Comment by vfalon** [comment]
@shrivabee can you please provide the link to the documentation that you are using?

**Comment by shrivabee** [comment]
Here it is : https://experienceleague.adobe.com/en/docs/experience-platform/sources/ui-tutorials/create/databases/sql-server

**Comment by shrivabee** [comment]
Moreover for the connection to work, does it have to be a sql native ( sql server authentication) or windows authentication would work?
I see IP whitelisting is a pre requisite now.
Please assist as we are in a middle of integration.

**Comment by carlojavier** [comment]
hey @shrivabee let me forward your questions to engineering and get back to you asap. thanks!

**Comment by carlojavier** [comment]
@shrivabee I have heard from sources engineering and they suggested that you file a support ticket as this may require some engineering troubleshooting. Also, do you have access to the internal slack? If so, please post your question about SQL native vs windows authentication in the #aep-sources-users channel for a quicker response. In the meantime, I will update the connection string examples

**Comment by vfalon** [comment]
Closing this issue. Descriptions and examples for MS SQL Server source have been updated.

API: https://experienceleague.adobe.com/en/docs/experience-platform/sources/api-tutorials/create/databases/sql-server#gather-required-credentials 

UI: https://experienceleague.adobe.com/en/docs/experience-platform/sources/ui-tutorials/create/databases/sql-server
