### ISSUE TITLE
Broken link on page: https://experienceleague.adobe.com/en/docs/core-services/interface/administration/ec-cookies/cookies-first-party

### ISSUE THREAD

**Issue by fitches** [AdobeDocs/experience-platform.en#342]
Issue in ./help/tags/extensions/client/web-sdk/web-sdk-extension-configuration.md

Edge domain: The domain that the extension sends and receives data from. Adobe recommends using a 1st-party domain (CNAME) for this extension. The default 3rd-party domain works for development environments but is not suitable for production environments. Instructions on how to set up a first-party CNAME are listed [here](https://experienceleague.adobe.com/en/docs/core-services/interface/administration/ec-cookies/cookies-first-party).

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-192337.

**Comment by vfalon** [comment]
@fitches the link you mentioned works fine. Closing this issue.
