### ISSUE TITLE
Mis-spelling

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#349]
Issue in ./help/xdm/field-groups/event/analytics-full-extension.md

https://experienceleague.adobe.com/en/docs/experience-platform/xdm/field-groups/event/analytics-full-extension#:~:text=the%20Analytics%20extension-,fieldl,-group.%20For%20more

The word "fieldl" has an extra l at the end.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-193659.

**Comment by vfalon** [comment]
Typo fixed. Closing this issue.
