### ISSUE TITLE
Include IdentityMap and endUserIDs field group in the sample payload

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#35]
Issue in ./help/ingestion/tutorials/streaming-time-series-data.md

It is very common and recommended best practice to include identityMap and endUserIDs field in the experience event records.

I am hoping we can add those fields with sample data in the sample payload shown on this page. 
Customers use this a ton to help get the right syntax for their experience events.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-119104.

**Comment by vfalon** [comment]
We've updated the documentation with the required information: https://experienceleague.adobe.com/docs/experience-platform/ingestion/tutorials/streaming-time-series-data.html#retrieve-the-newly-ingested-time-series-data. Closing the issue.
