### ISSUE TITLE
Nevigation links not working on search result pages

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#35]
Example: when searching for 'RBAC' no results are found so try to navigate back to docs via top nav, but nav links do not work, instead only append a '#' to the URL of the current page, example:

Issue in help/en/experience-platform/search.html?q=rbac&_charset_=UTF-8
select nav link goes to
help/en/experience-platform/search.html?q=rbac&_charset_=UTF-8#

this occurs on both successful search results page and non successful results pages

https://docs.adobe.com/content/help/en/experience-platform/search.html?q=access&_charset_=UTF-8

**Comment by djwendo** [comment]
This is a known issue with search on docs.adobe.com that should be resolved with the update coming in early October.

cc @bbringhu

**Comment by iandejong** [comment]
Hi Wendy
 Can you please re open the ticket until the issue has been confirmed to be
resolved after the release.

 closing before the issue is actually fixed could leave gaps and remaining
issues if not confirmed before closing.

Thanks
Ian
