### ISSUE TITLE
Documentation Says Bot flag will always be "1" but when testing it is coming as '0.0'

### ISSUE THREAD

**Issue by mtummala54** [AdobeDocs/experience-platform.en#352]
Issue in ./help/datastreams/bot-detection.md

We are testing the bot detection feature in AEP, documentation says if it matches any bot rules it will return "1" but when testing it, it is returning "0.0" could you please confirm what is the right value?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-194350.

**Comment by vfalon** [comment]
If the bot rules are matched, the scoring will be 1. If it returns 0, then the rules are not matched. We've validated this with the engineering team and the documentation is correct. If you need further assistance in investigating this issue, please contact the Adobe support team. Closing this issue.
