### ISSUE TITLE
First note on this page could use some clarification

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/experience-platform.en#358]
Issue in ./help/destinations/catalog/personalization/custom-personalization.md

This line in the first note:

"If you are already using Web SDK or Mobile SDK for your integration, you can retrieve attributes via the Server API by adding a server-side integration."

..is causing some concern with a customer. Some are taking this to mean that because the WebSDK and Mobile SDK libraries are deployed, they can be used instead of a server-side integration to retrieve attributes. While I don't see it that way, I can see how the wording may be construed to mean that. Perhaps a more clear sentence would be:

"You can retrieve attributes via the Server API by adding a server-side integration that utilizes an existing datastream that may already be deployed in conjunction with a Web or Mobile SDK implementation" 

The idea we want to explain is that an existing datastream (which is a requirement for using the Web and Mobile SDKs) can be used to create a server-side integration. The unfortunate connection being drawn is that deploying the Web and Mobile SDK libraries is what enables the retrieval of attributes.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-197237.

**Comment by vfalon** [comment]
Updated the note to make things clearer. Closing this issue.
