### ISSUE TITLE
404 error on Source Connectors link

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#36]
On the page
https://www.adobe.io/apis/experienceplatform/home/services.html
the link to 'Source Connectors' (under Data ingestions) sends users to the following page which throws a 404 
https://docs.adobe.com/content/help/en/experience-platform/source-connectors/home.html

**Comment by djwendo** [comment]
The goURL has been updated and will point to the correct link within 24 hrs. In the meantime, Sources documentation can be found here: https://docs.adobe.com/content/help/en/experience-platform/sources/home.html

**Comment by iandejong** [comment]
Hi Wendy
 Can you please re open the ticket until the issue has been confirmed to be
resolved after the release.

 closing before the issue is actually fixed could leave gaps and remaining
issues if not confirmed before closing.

Thanks
Ian

**Comment by djwendo** [comment]
The link is confirmed to be working. This issue is resolved.
