### ISSUE TITLE
Correction required in the retrieve failed batch api request

### ISSUE THREAD

**Issue by stripathi345** [AdobeDocs/experience-platform.en#36]
Issue in ./help/ingestion/quality/retrieve-failed-batches.md

In the “Retrieve the failed batch” api request, a double quote is missing for sandbox name, this results to an error while importing the curl request.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-119103.

**Comment by vfalon** [comment]
The documentation was updated. Closing this issue.
