### ISSUE TITLE
event type decisioning.propositionFetch is missing in Accepted values for eventType

### ISSUE THREAD

**Issue by manishadb** [AdobeDocs/experience-platform.en#360]
Issue in ./help/xdm/classes/experienceevent.md

**decisioning.propositionFetch** is missing in Accepted values for eventType 

More details for decisioning.propositionFetch is given at below link 
https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/use-cases/top-bottom-page-events

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-197238.

**Comment by vfalon** [comment]
We've reviewed and updated the documentation. Closing this issue.
