### ISSUE TITLE
The action type "Send event" does not match the current UI

### ISSUE THREAD

**Issue by immany** [AdobeDocs/experience-platform.en#361]
Issue in ./help/tags/extensions/client/web-sdk/action-types.md

Please update the items of action type "Send event" to match the current UI.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-197239.

**Comment by vfalon** [comment]
We've updated the documentation to reflect the current UI. Closing this issue.
