### ISSUE TITLE
Azure Data Factory to Data Landing Zone not supported

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#362]
A client is trying setting up an Azure Data Factory to DLZ file transfer.
ADF SAS requires storage level access: "The type property must be set to AzureBlobStorage (suggested) or AzureStorage (see the following note). [1]".

As per this case [2] Adobe does not support storage level access: "we can't provide storage level access to DLZ"

Could we include such explicit limit in the very same way the article includes "Private links" limit important remark?

Issue in ./help/sources/connectors/cloud-storage/data-landing-zone.md

[1]: https://learn.microsoft.com/en-us/azure/data-factory/connector-azure-blob-storage?tabs=data-factory#shared-access-signature-authentication
[2]: https://jira.corp.adobe.com/browse/PLATIR-24116

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-197240.

**Comment by vfalon** [comment]
We've added guidance on how to use DLZ and ADF concurrently. Closing this issue.
