### ISSUE TITLE
SAS or SaaS

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/experience-platform.en#364]
Issue in ./help/destinations/catalog/cloud-storage/data-landing-zone.md

Is the authentication for data landing zone **SAS**-based authentication as stated on the page or is it **SaaS**-based authentication? SAS is software product for data analytics that also has its own authentication so we should clarify whether this is their authentication or Software As A Service based authentication.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-197541.

**Comment by vfalon** [comment]
We've updated the documentation to clarify the meaning of SAS. As mentioned in the documentation, Data Landing Zone is an Azure Blob storage interface. In the context of Azure Blob, SAS stands for Shared Access Signature (https://learn.microsoft.com/en-us/azure/ai-services/translator/document-translation/how-to-guides/create-sas-tokens?tabs=Containers).

Closing this issue.
