### ISSUE TITLE
Data lineage verbiage should not imply violations are possible

### ISSUE THREAD

**Issue by qualitybydesign** [AdobeDocs/experience-platform.en#366]
Issue in ./help/data-governance/enforcement/auto-enforcement.md

in the data lineage section there's several explanations like 

"Policy violations will occur if you activate an audience whose inherited labels are restricted by the target destination’s applicable policies, based on its marketing use case."

These imply that you can activate an audience that violates a policy.  That is not the case; the activation will be prevented by the violation.  It would be better so say something like: "...if you _**attempt to**_ activate an audience..." (without the **_emphasis_**)

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-199454.

**Comment by vfalon** [comment]
We've reviewed and updated the documentation. Closing this issue.
