### ISSUE TITLE
Page section repeated by mistake

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/experience-platform.en#367]
Issue in [./help/web-sdk/faq.md](./help/web-sdk/faq.md)

Looks like https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/faq#support-internet-explore has the first part of "Supporting Internet Explorer" section twice by mistake.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-199453.

**Comment by vfalon** [comment]
Removed the duplicate content. Closing this issue.
