### ISSUE TITLE
remove x-sandbox-name from list of required headers for list and lookup

### ISSUE THREAD

**Issue by krhoton-adobe** [AdobeDocs/experience-platform.en#368]
Issue in ./help/sandboxes/api/sandboxes.md

The documentation for listing all sandboxes and fetching a single sandbox details both list 'x-sandbox-name' as a required header, when it is not required and is ignored if provided.  Lookup gets the sandbox name from the URL path, and listing will return all sandboxes, so it doesn't make sense to supply a single one.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-199452.

**Comment by vfalon** [comment]
We've updated the documentation accordingly. Closing this issue.
