### ISSUE TITLE
Id graph processing time

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#369]
Issue in ./help/identity-service/guardrails.md

On this page can we specify the guardrail for how long and what the high end supported throughput we can expect from identity graph?
For both streaming and batch.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-199449.

**Comment by vfalon** [comment]
The recommendation from Product is to not include this information at this time. Closing this issue.
