### ISSUE TITLE
Journey Orchestration not found via search

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#37]
See search query: https://docs.adobe.com/content/help/en/experience-platform/search.html?q=journey+orchestration&_charset_=UTF-8

for some reason CJA comes up instead only

**Comment by djwendo** [comment]
Similar to Issue #39 there are known issues with the search results returning in docs.adobe.com. This should be resolved soon. 

The Journey Orchestration guide can be found here: https://docs.adobe.com/content/help/en/journeys/using/journey-orchestration-home.html

**Comment by iandejong** [comment]
Hi Wendy
 Can you please re open the ticket until the issue has been confirmed to be
resolved after the release.

 closing before the issue is actually fixed could leave gaps and remaining
issues if not confirmed before closing.

Thanks
Ian
