### ISSUE TITLE
Multiple primary IDs in WebSDK example for FPID

### ISSUE THREAD

**Issue by raresvla** [AdobeDocs/experience-platform.en#371]
Issue in ./help/web-sdk/identity/first-party-device-ids.md

The example in the [Using FPIDs in identityMap](https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/identity/first-party-device-ids#identityMap) section is misleading, since it's having multiple IDs marked as primary.

When an authenticated ID is present on the call, it should be the only one marked as primary. Therefore, the example needs to be updated as follows:
```json
{
  "identityMap": {
    "FPID": [
      {
        "id": "123e4567-e89b-42d3-9456-426614174000",
        "authenticatedState": "ambiguous",
        "primary": false
      }
    ],
    "EMAIL": [
      {
        "id": "email@mail.com",
        "authenticatedState": "authenticated",
        "primary": true
      }
    ]
  }
}
```

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-201354.

**Comment by vfalon** [comment]
Thanks for providing the correct sample! I've updated the page and closing the issue.
