### ISSUE TITLE
Bad Request link found on https://www.adobe.com/au/experience-platform/documentation-and-developer-resources.html

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#38]
the "View all documentation" link under "Access User Guides" on the following page sends a 'Bad Request'
https://www.adobe.com/au/experience-platform/documentation-and-developer-resources.html

the link goes to : https://www.adobe.com/go/platform-home-en
this give a bad request page

please update link

**Comment by djwendo** [comment]
The links appear to be working properly. I am unable to recreate this error. @iandejong , can you please try the links again and confirm if this is still an issue?

**Comment by iandejong** [comment]
unfortunately i still see the issue, see screenshots

![image](https://user-images.githubusercontent.com/51468975/94643539-61d83080-032a-11eb-8cae-42be5e375c29.png)


![image](https://user-images.githubusercontent.com/51468975/94643566-71f01000-032a-11eb-939d-edfa307e584a.png)

**Comment by djwendo** [comment]
Interesting, it's still working properly for me. Can you try going to https://www.adobe.com/go/platform-home-en and see if that links works for you at all? That's the GoURL that link is apparently pointing to.

**Comment by iandejong** [comment]
Interesting – this link (https://www.adobe.com/go/platform-home-en<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.adobe.com%2Fgo%2Fplatform-home-en&data=02%7C01%7Cidejong%40adobe.com%7C6b9107a0b44d4c550b0308d8658c0506%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637370999382702509&sdata=KQFWQR6cwoJA%2Fd6uh8lNmycZBsMatzhtcfy47zX4Mww%3D&reserved=0> ) works for me ok and re-directs to https://docs.adobe.com/content/help/en/experience-platform/landing/home.html

When I look at the page https://www.adobe.com/au/experience-platform/documentation-and-developer-resources.html and hover over “View all documentation”, the following URL shows in the bottom left suggesting this is the URL: https://www.adobe.io/apis/experienceplatform/home/workflows.html

But now for some reason works and also re-directs to https://docs.adobe.com/content/help/en/experience-platform/landing/home.html

Strange but working – please feel free to close ticket – thanks!


Thanks
Ian

Ian Dejong  |  APAC Multi Solution Expert SC  |  Adobe  |  +61 40 569 6840 | idejong@adobe.com<mailto:idejong@adobe.com>
