### ISSUE TITLE
Correct the document: Is this feature still in Beta?

### ISSUE THREAD

**Issue by yulia-levy** [AdobeDocs/experience-platform.en#380]
The documentation says that Computed Attributes feature is in Beta. As far as I know, this feature is in GA.

Issue in ./help/profile/api/overview.md

**Comment by andreyfmc** [comment]
install this
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-205498.

**Comment by vfalon** [comment]
We've updated the documentation to reflect the GA availability of this feature.
