### ISSUE TITLE
Assurance - User Access.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#381]
Issue in ./help/assurance/user-access.md

Per Amber Hardy in engineering - "A user just needs to be added to any product profile and they will have access to Assurance. It doesn't need to be the "AEP-Default-All-Users" product profile. Just any product profile."

This guide needs to be updated to reflect this as the guide suggests that a user must be added to the "AEP-Default-All-Users" product profile and that implies that this is the only product profile that will work.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-207407.

**Comment by vfalon** [comment]
We've updated the documentation with the correct information. Closing this issue.
