### ISSUE TITLE
out-of-date note about Schema-based labeling

### ISSUE THREAD

**Issue by qualitybydesign** [AdobeDocs/experience-platform.en#382]
Issue in ./help/xdm/tutorials/labels.md

This page has a note that reads:

> IMPORTANT
> Schema-based labeling is part of [attribute-based access control](https://experienceleague.adobe.com/en/docs/experience-platform/access-control/abac/overview), which is currently available in a limited release for US-based healthcare customers. This capability will be available to all Adobe Real-Time Customer Data Platform customers once it is fully released.

This feature has been fully released and is available to all Adobe Real-Time Customer Data Platform customers in all regions.  Please remove this note wherever it appears

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-207408.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated it to reflect the availability. Closing this issue.
