### ISSUE TITLE
Old format referenced

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#383]
Issue in ./help/ingestion/tutorials/streaming-time-series-data.md

Under the "Ingest time series data to the streaming connection" section, an example is provided of the payload format. 
The format shown references the old method of format. Which is still compatible, but more complicated and cumbersome for customers to implement. There is a new much simpler version as outlined below. I also notice that I can not find anywhere in the docs where the new version is referenced.

It shows having to include the following - 
-d '{
    "header": {
        "schemaRef": {
            "id": "{SCHEMA_REF_ID}",
            "contentType": "application/vnd.adobe.xed-full+json;version=1"
        },
        "flowId": "{FLOW_ID}",
        "datasetId": "{DATASET_ID}"
    },

But the new format allows the following instead. Notice no schema ref or ID is needed. Just the datasetid, flowid, and imsOrgID.

{
    "header": {
        "datasetId": "65295b10343dd228d35268df",
        "flowId": "caa0eb1d-58e2-4c21-9ad0-cb7c2926a9f0",
        "imsOrgID": "2DE02902644AEAE30A495FB9@AdobeOrg"
    }

A similar example if shown in the streaming multiple messages doc.
https://experienceleague.adobe.com/en/docs/experience-platform/ingestion/tutorials/streaming-multiple-messages

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-207409.

**Comment by vfalon** [comment]
We've updated the documentation with the right format: https://experienceleague.corp.adobe.com/docs/experience-platform/ingestion/tutorials/streaming-time-series-data.html#ingest-time-series-data-to-the-streaming-connection.

Closing this issue.
