### ISSUE TITLE
Links not working on Release Notes page

### ISSUE THREAD

**Issue by bpro0121** [AdobeDocs/experience-platform.en#385]
Issue in ./help/release-notes/latest/latest.md
https://experienceleague.adobe.com/en/docs/experience-platform/release-notes/latest#dashboards-dashboards
The 9 links at the start of the page are not working (it looks like the section name is repeated at the end of each link).

![image](https://github.com/user-attachments/assets/3daa9616-0c7c-407e-8162-84f00af25d93)

For example, the link to go to Alerts is 
https://experienceleague.adobe.com/en/docs/experience-platform/release-notes/latest#alerts-alerts

It should be 
https://experienceleague.adobe.com/en/docs/experience-platform/release-notes/latest#alerts

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-207413.

**Comment by vfalon** [comment]
This issue has since been fixed. Closing this issue.
