### ISSUE TITLE
Is this about Query Service or Cloud Storage IP Allow list?

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/experience-platform.en#386]
Issue in ./help/query-service/ip-address-allowlist.md

This url https://experienceleague.adobe.com/en/docs/experience-platform/query/ip-address-allowlist points to query service, but in the content, inside the 'Important' box, it talks about Cloud Storage. I am very confused. Which IP Allowlist is this referring to? Is this Query Service, or Cloud Storage?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-207415.

**Comment by vfalon** [comment]
We've updated the documentation to clarify the applicability of the allow list.
