### ISSUE TITLE
HTLM in-page anchors displayed in the summary links

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#387]
Good day team.
The HTML in-page anchors are displayed in the summary links:

EG: 
![image](https://github.com/user-attachments/assets/940ab82f-6faf-4f7b-a80d-7044957c00dd)

![image](https://github.com/user-attachments/assets/51063207-4052-4b35-bb51-baa7ac36d83c)

Could you please remove the " {#anchor-name}" section from the anchors text?

Issue in ./help/release-notes/latest/latest.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-207416.

**Comment by vfalon** [comment]
This issue has been fixed. Closing.
