### ISSUE TITLE
HTLM in-page anchors displayed in headings - ref  #387

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-platform.en#389]
Good day team.
I found another occurrence of the recently solved #387.

Anchors' refs are displayed in the heading on this page:

![image](https://github.com/user-attachments/assets/1374f514-1143-40e5-8ec0-ca7c17dd027b)

Could this be a more extended behavior, affecting even more pages, due to any mis-configuration on the anchors rendition logic?

Issue in ./help/profile/merge-policies/overview.md

**Comment by vfalon** [comment]
This is an Experience League bug that is currently being worked on. Closing the issue.
