### ISSUE TITLE
For most instances

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#394]
Issue in ./help/segmentation/api/streaming-segmentation.md

Can more specificity be added for the following sentence?

"For most instances, streaming segmentation unqualification happens in real-time. However, streaming segment definitions that use segments of segments do not unqualify in real-time, instead unqualifying after 24 hours."

The phrase "for most instances" causes confusion as the system should operate predictably and deterministically. 
Are there specific instances where unqualification is not expected to happen in real time.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-211360.

**Comment by vfalon** [comment]
The instances where unqualification doesn't happen in real time is contained in the second phrase. **"However, streaming segment definitions that use segments of segments do not unqualify in real-time, instead unqualifying after 24 hours."**

Closing this issue.
