### ISSUE TITLE
applyPropositiions

### ISSUE THREAD

**Issue by ericthibeault-adobe** [AdobeDocs/experience-platform.en#396]
Issue in ./help/web-sdk/commands/applypropositions.md

In the payload example, applyPropositiions is wrongly spelled.  2 "i".

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-212864.

**Comment by vfalon** [comment]
This issue is now fixed. Closing.
