### ISSUE TITLE
Incorrect personalization flag attributes

### ISSUE THREAD

**Issue by bennet-roy** [AdobeDocs/experience-platform.en#397]
Issue in ./help/web-sdk/personalization/display-events.md

On this page, there are mentions of `personalization.sendDisplayNotifications` and `personalization.includePendingDisplayNotifications` flags, but I don't see these flags in the alloyJS code.  I am guessing these should be `personalization.sendDisplayEvent` and `personalization.includeRenderedPropositions`. Please clarify and add corrections to the docs if needed.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-212878.

**Comment by vfalon** [comment]
We've updated the documentation with the correct attributes. Closing the issue.
