### ISSUE TITLE
Add information about the C10 label

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#4]
Issue in help/data-governance/labels/reference.md

**Comment by djwendo** [comment]
@dwright-adobe our understanding was that the C10 label was not customer-facing yet and that only one internal client was using it (And for that one customer, the label is not accessible in the UI, it is applied behind the scenes). Can you confirm if/where there is public usage of the C10 label? cc @pnolan89

**Comment by dwright-adobe** [comment]
@djwendo , I believe it's related to the new Merge Policies capability. Note that a merge policy with C10 is shown on the screenshots here: https://docs.adobe.com/content/help/en/experience-platform/data-governance/policies/user-guide.html

**Comment by djwendo** [comment]
This has been published and is now live on docs.adobe: https://docs.adobe.com/content/help/en/experience-platform/data-governance/labels/reference.html#contract-labels
