### ISSUE TITLE
Data Science Workspace Disclaimer missing

### ISSUE THREAD

**Issue by StrawberryBe** [AdobeDocs/experience-platform.en#400]
Issue in ./help/xdm/home.md morespecifically issue here: https://experienceleague.adobe.com/en/docs/experience-platform/xdm/home#:~:text=for%20more%20information.-,Data%20Science%20Workspace,-Adobe%20Experience%20Platform

As Adobe is no longer selling Datascience Workspace I would suggest adding a disclaimer stating, "Data Science Workspace is no longer available for purchase. This documentation is intended for existing customers with prior entitlements to Data Science Workspace."

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-212879.

**Comment by vfalon** [comment]
We've updated the documentation with the disclaimer suggestion. Closing this issue.
