### ISSUE TITLE
24 hour clarification

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#401]
Issue in ./help/segmentation/api/edge-segmentation.md

The doc says,

Segment of segments
"Any segment definition that contains one or more batch or streaming segments. Note: If a segment of segments is used, profile disqualification will happen every 24 hours."

This leads customers to believe that if a segment is comprised of "segment of segments" it will not be able to exit the segment until up to 24 hours.

But if all children segments in a segment of segment are streaming or edge based, the segment of segments will immediately disqualify. 

We should clarify this in the docs so customers are not confused that disqualification for these types of segments can take up to 24 hours.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-213015.

**Comment by vfalon** [comment]
We've updated the docs to reflect the request.
