### ISSUE TITLE
Misspelling on page

### ISSUE THREAD

**Issue by smshatz** [AdobeDocs/experience-platform.en#405]
Issue in ./help/rtcdp/b2b-tutorial.md

under the Getting Started section there is a link to [Experience Data Modal (XDM)] https://experienceleague.adobe.com/en/docs/experience-platform/xdm/home), which should be Model not Modal.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-215767.

**Comment by vfalon** [comment]
Typo fixed. Closing this issue.
