### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by LeanTvener11** [AdobeDocs/experience-platform.en#406]
Issue in ./help/tags/extensions/client/web-sdk/overview.md

there is no content on this page about tags. I dont get it if there is or how it explains tags

**Comment by vfalon** [comment]
The page is part of the Web SDK Tag Extension section. Everything in that section refers to the Web SDK tag extension. As the page says, "For details about configuring the Platform Web SDK extension, see the [Configure the Web SDK tag extension](https://experienceleague.adobe.com/en/docs/experience-platform/tags/extensions/client/web-sdk/web-sdk-extension-configuration)."

Closing this issue.
