### ISSUE TITLE
Missing item on automatically mapped Analytics variables page

### ISSUE THREAD

**Issue by jklockow** [AdobeDocs/experience-platform.en#41]
Issue in help/edge/solution-specific/analytics/automatically-mapped-vars.md

This page contains an entry for serialization of the scCart event: commerce.productListViews.id, but it does not contain an entry for the scCart view, unserialized, which is how most people will use it. I was able to confirm that commerce.productListViews does actually set that event, however, so it's just a documentation issue.

**Comment by djwendo** [comment]
Thank you. Tracking in https://jira.corp.adobe.com/browse/PLAT-71634

**Comment by Joshua-McGee** [comment]
@jklockow Just to clarify, were you trying to provide your own ID value when mapping your analytics data to XDM? Was the problem that it is not clear that commerce.productListViews.id is a system-generated value? Or are there missing paths?

**Comment by jklockow** [comment]
Hi Joshua,

My comment was not actually about the role of commerce.productListViews.id at all, although I did not realize that the id is a system-generated value. My comment was that commerce.productListViews (the even without the id), is not mentioned in the doc. Seems like an oversight since other similar events are listed.

**Comment by pnolan89** [comment]
Doc has been updated to clarify how the system handles unserialized items and the use of the `id` field in general: https://docs.adobe.com/content/help/en/experience-platform/edge/data-collection/adobe-analytics/automatically-mapped-vars.html
