### ISSUE TITLE
Segmentation guardrails are incorrect

### ISSUE THREAD

**Issue by betabloch** [AdobeDocs/experience-platform.en#41]
Issue in ./help/profile/guardrails.md

As part of Sanoma CERT process we were informed that there are hard limits on how many segments that can be in a segment. That there is a hard limit of (about) 1600 segments per sandbox, not the 10000 soft limit as detailed in the segmentation guardrails.

Customers like Sanoma do check these docs, and its difficult when they are within the limits as documented, and it's causing the seg service to fall over.  Can the segmentation limits be updated to what engineering says are the actual limits and that these limits are hard not soft.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-120493.

**Comment by vgiurgiu** [comment]
Closing this issue. Please see and follow the segments per sandbox guardrails, which are up-to-date here:
https://experienceleague.adobe.com/docs/experience-platform/profile/guardrails.html?lang=en#segmentation-guardrails
