### ISSUE TITLE
identity limit question

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#42]
Issue in ./help/identity-service/guardrails.md

Is this identity limit at the IMS org level or the sandbox level? 
Meaning each profile in each sandbox gets 150, or a single profile only gets 150 identities across all sandboxes in a IMS org.

Can we add this detail to the docs?

Number of identities in a graph | 150
-- | --

**Comment by carlojavier** [comment]
@nhecht thanks for calling this out. Document has been updated with the clarification here: https://experienceleague.adobe.com/docs/experience-platform/identity/guardrails.html?lang=en
