### ISSUE TITLE
View a specific delete request sample curl API command should be GET and not POST

### ISSUE THREAD

**Issue by praveenpenupati** [AdobeDocs/experience-platform.en#44]
Issue in ./help/profile/api/profile-system-jobs.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-121643.

**Comment by vfalon** [comment]
Documentation was reviewed and updated. Closing the issue.
