### ISSUE TITLE
Missing information on the Privacy JS API

### ISSUE THREAD

**Issue by pitchmuc** [AdobeDocs/experience-platform.en#44]
Issue in help/privacy-service/js-library.md

On the Privacy JS, it said that to instantiate the library, you should use the following code:
var adobePrivacy = new AdobePrivacy({
    imsOrgID: "{IMS_ORG}",
    key: "{DATA_SUBJECT_ID}",
    reportSuite: "{REPORT_SUITE_ID}",
    trackingServer: "{SERVER_URL}",
    clientCode: "{TARGET_CLIENT_CODE}"
});

However, there is no information on what the DATA_SUBJECT_ID is. 
Could you please add it on the page ? 

Thanks

**Comment by djwendo** [comment]
Thank you for providing this feedback, we will work to update the documentation accordingly. We are tracking the doc update here: https://jira.corp.adobe.com/browse/PLAT-73104

**Comment by pnolan89** [comment]
The `key` field was added erroneously in the initial draft--it is not required to instantiate the Privacy object. It's been removed from the live doc: https://docs.adobe.com/content/help/en/experience-platform/privacy/js-library.html
