### ISSUE TITLE
JASON example

### ISSUE THREAD

**Issue by inge-ecxio** [AdobeDocs/experience-platform.en#45]
Issue in help/intelligent-services/data-preparation.md

JASON example url is broken, 404 page is dispayed if you click on it. 

It's not clear that the data set created will appear under data sources >> unkown, would be nice if you add this

**Comment by djwendo** [comment]
Thank you for reporting this issue. We will work to update the documentation accordingly. The updates are being tracked internally here: https://jira.corp.adobe.com/browse/PLAT-73106

**Comment by Joshua-McGee** [comment]
@inge-ecxio Thanks for reporting this issue. Would you be able to elaborate on what you mean by the dataset created appears under data sources >> unknown? The current documentation assumes that you create your dataset based on the CEE schema and once you create the dataset it should be viewable from the Platform UI within the **Datasets** workspace.

https://docs.adobe.com/help/en/experience-platform/intelligent-services/data-preparation.html#create-a-cee-schema-and-dataset

**Comment by Joshua-McGee** [comment]
The JSON url is no longer broken: https://docs.adobe.com/content/help/en/experience-platform/intelligent-services/data-preparation.html#cee-schema

I was unable to re-create a dataset with an unknown data source. If this continues to be a problem, please open a new issue and include as much information as possible such as screenshots and any error codes you encounter.
Thanks
