### ISSUE TITLE
productlistitems.[N].lineitemid does not exist on productListItem datatype

### ISSUE THREAD

**Issue by stewartschillingsdi** [AdobeDocs/experience-platform.en#49]
Issue in help/edge/data-collection/adobe-analytics/automatically-mapped-vars.md

productlistitems.[N].lineitemid | products | AppMeasurement query parameter Products Category mapping.
Also, pricetotal should be camelcase "priceTotal"
![Screen Shot 2020-10-29 at 1 34 57 PM](https://user-images.githubusercontent.com/22940746/97617508-d9fa4a80-19eb-11eb-8d36-d4ae419bf81a.png)

**Comment by djwendo** [comment]
Thank you for reporting this issue. We will work to update the documentation accordingly.

Internal reporting: https://jira.corp.adobe.com/browse/PLAT-73110

**Comment by Joshua-McGee** [comment]
Thank you for reporting this issue. The documentation has been updated and can be seen here: https://docs.adobe.com/content/help/en/experience-platform/edge/data-collection/adobe-analytics/automatically-mapped-vars.html
