### ISSUE TITLE
rule stash object custom code typo

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/experience-platform.en#50]
Issue in ./help/tags/extensions/web/core/event-forwarding.md

Is the rulestash object custom code sample correct? Seems like it is supposed to be a reference to recalling the rulestash something more like: arc.ruleStash['adobe-cloud-connector'].

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-122354.

**Comment by vfalon** [comment]
The documentation was reviewed and updated accordingly. Closing this issue.
