### ISSUE TITLE
Missing release notes for v0.17.2

### ISSUE THREAD

**Issue by mpspencer** [AdobeDocs/experience-platform.en#51]
Issue in ./help/tags/extensions/web/target-v2/release-notes.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-122352.

**Comment by vfalon** [comment]
We've reviewed the release notes and updated the page. Closing this issue.
