### ISSUE TITLE
URL landing on wrong page (observability/metrics.html)

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#53]
Issue in ./help/observability/api/overview.md

this page links to the swagger API for observability metrics, within that doc, under GET, the 'metrics' variable has a link pointing to
https://docs.adobe.com/content/help/en/experience-platform/observability/metrics.html

this URL redirects to experienceleague homepage or profile page if i'm logged in. instead of directing to the actual metrics doc

**Comment by djwendo** [comment]
Thank you for reporting this error. We are reviewing the documentation and will resolve.

Tracking internally here: https://jira.corp.adobe.com/browse/PLAT-79338

**Comment by pnolan89** [comment]
Link has been fixed: https://www.adobe.io/apis/experienceplatform/home/api-reference.html#!acpdr/swagger-specs/observability-insights.yaml
