### ISSUE TITLE
bad path in request call example

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/experience-platform.en#53]
Issue in ./help/server-api/interactive-data-collection.md
The curl URL path in the API Call Request example is missing the "/ee" folder like is noted in the API format above. This leads to a 404 response.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-124069.

**Comment by vfalon** [comment]
The documentation was updated with the correct paths. Closing this issue.
