### ISSUE TITLE
Streaming segment documentation

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#56]
Issue in ./help/segmentation/ui/streaming-segmentation.md

The details in the streaming query types look like they are unrelated to this topic.
"Incoming hit that refers to a profile within a relative window | A segment definition that includes Adobe Audience Manager (AAM) segments or traits."

I don't follow what AAM has to do with this specific rule.

Query type | Details
-- | --
Incoming hit that refers to a profile within a relative window | A segment definition that includes Adobe Audience Manager (AAM) segments or traits.
Multiple events that refer to a profile | A segment definition that includes Adobe Audience Manager (AAM) segments or traits.
Multi-entity queries | Multi-entity queries are, as a whole, not supported by streaming segmentation.

**Comment by djwendo** [comment]
Tracking resolution in https://jira.corp.adobe.com/browse/PLAT-79339

**Comment by djwendo** [comment]
This is resolved. The streaming segmentation docs have been updated as needed.
