### ISSUE TITLE
Segment Job API doesn't match Segment developer guide

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#57]
Issue in ./help/segmentation/api/segment-jobs.md

The segment job API says I need to add the below header to the API call but the developer guide does not include this in the examples. and the API did not specify example values.
x-profile-instance-id 
*string(header) | The ID of the Profile Instance.

https://www.adobe.io/apis/experienceplatform/home/api-reference.html#/Segment_jobs/postSegmentJob

**Comment by djwendo** [comment]
Thank you for reporting this. Tracking update work in https://jira.corp.adobe.com/browse/PLAT-79337

**Comment by djwendo** [comment]
This has been resolved and the changes should now appear live on adobe.io. https://www.adobe.io/apis/experienceplatform/home/api-reference.html#/Segment_jobs/postSegmentJob
