### ISSUE TITLE
Incorrect API syntax for Update schedule state

### ISSUE THREAD

**Issue by praveenpenupati** [AdobeDocs/experience-platform.en#58]
Issue in ./help/segmentation/api/schedules.md

Sample API syntax for Update schedule state reads as curl -X DELETE https://platform.adobe.io/data/core/ups/config/schedules/4e538382-dbd8-449e-988a-4ac639ebe72b and this should be 
curl -X PATCH https://platform.adobe.io/data/core/ups/config/schedules/4e538382-dbd8-449e-988a-4ac639ebe72b \

Please correct.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-124067.

**Comment by vfalon** [comment]
The documentation was reviewed and updated to reflect the correct syntax. Closing this issue.
