### ISSUE TITLE
I want to know which storage used to store customer's profile data?

### ISSUE THREAD

**Issue by cangchen8180** [AdobeDocs/experience-platform.en#58]
Issue in ./help/profile/home.md

**Comment by djwendo** [comment]
Thank you for logging this issue. To clarify, are you wanting to know the type of storage used for Profile data? Real-time Customer Profile is running on an Azure Cosmos DB infrastructure. Please let me know if that is the information you are looking for and we could add that to the profile overview if you feel that would be helpful.

**Comment by djwendo** [comment]
Information regarding the Profile store infrastructure has been added to the Real-time Customer Profile overview documentation. I hope this resolves the issue that you have logged. If it does not, please open a new issue and we will try to address your needs. Thanks!

Profile overview: https://experienceleague.adobe.com/docs/experience-platform/profile/home.html?lang=en#understanding-profiles
