### ISSUE TITLE
CSM Acronym

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/experience-platform.en#59]
Issue in ./help/edge/fundamentals/prerequisite.md

In this page the CSM acronym is explained as Certified Software Manager, while, due to the context, I guess it should be Customer Success Manager.

**Comment by djwendo** [comment]
Thank you for reporting this. We will review the documentation and update as needed. 

Internally tracking in https://jira.corp.adobe.com/browse/PLAT-79336

**Comment by djwendo** [comment]
This has been corrected in the documentation.
https://experienceleague.adobe.com/docs/experience-platform/edge/fundamentals/prerequisite.html?lang=en#fundamentals
