### ISSUE TITLE
Is Server side API and Web/SDK supported?

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#59]
Issue in ./help/data-prep/upserts.md

The document outlines that the HTTP API is supported for data prep. But is the server side API and Edge Web SDK also supported?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-124066.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated the limitations section of the upserts document to note that upserts currently do not support SDKs. Closing the issue.
