### ISSUE TITLE
Documentation says that upsert supported for streaming when it is not.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#6]
Issue in ./help/catalog/datasets/enable-upsert.md

The documentation says this is supported for streaming when it is not.

"Next Steps
Your Profile and upsert-enabled dataset can now be used by batch and streaming ingestion workflows to make updates to profile data. To learn more about ingesting data into Adobe Experience Platform, please begin by reading the data ingestion overview."

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-113827.

**Comment by vfalon** [comment]
@nhecht the documentation team has verified this information, and the documentation is correct.

Upsert can be used for streaming, but users don't need to enable this at the dataset level. It depends on the type of message you pass along that determines whether its a `patch` or a `put` operation. `Patch` in streaming has been in a place for a very long time.

Closing this ticket.
