### ISSUE TITLE
how to request WebSDK? is this through the CSM as in "Customer Success Manager", or really through some "Certified software manager (CSM)"?

### ISSUE THREAD

**Issue by rwunsch** [AdobeDocs/experience-platform.en#60]
Issue in ./help/edge/web-sdk-faq.md

The page on WebSDK [0] claims that it can be requested through a ""Certified software manager (CSM)", which is confusing me.

Do you mean the "customer success manager" (CSM)? 
This would be a much more likely option/title/person to request access to WebSDK.

Thanks and cheers - Robert

[0] https://experienceleague.adobe.com/docs/experience-platform/edge/web-sdk-faq.html?lang=en#how-do-i-get-access-to-start-using-adobe-experience-platform-web-sdk%3F

**Comment by djwendo** [comment]
Thank you reporting this. We will review and update the information as soon as possible to make it more clear.

**Comment by djwendo** [comment]
Internal tracking in https://jira.corp.adobe.com/browse/PLAT-79336

**Comment by djwendo** [comment]
This has been corrected. The documentation now makes it more clear how to access the Web SDK.
https://experienceleague.adobe.com/docs/experience-platform/edge/web-sdk-faq.html?lang=en#how-do-i-get-access-to-start-using-adobe-experience-platform-web-sdk%3F
