### ISSUE TITLE
Is valid identities also a data quality check

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#61]
Issue in ./help/ingestion/quality/overview.md

![image](https://user-images.githubusercontent.com/81246645/169346671-5646ebc5-a64e-42c5-873b-91340a73530c.png)

It shows that ECID must be certain number of characters or else UIS will reject it.
My understanding is valid email is also checked for email namespace type.

It would be helpful to include these validation checks in the documentation here.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-124065.

**Comment by vfalon** [comment]
We've updated the documentation and will close this issue.
