### ISSUE TITLE
Site Search Data type links to Field Group

### ISSUE THREAD

**Issue by djselby** [AdobeDocs/experience-platform.en#63]
Issue in ./help/release-notes/latest/latest.md

The Site Search Data type links to https://github.com/adobe/xdm/blob/master/components/fieldgroups/experience-event/experienceevent-site-search.schema.json

I believe that should be https://github.com/adobe/xdm/blob/master/components/datatypes/sitesearch.schema.json

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-126087.

**Comment by vfalon** [comment]
We're reviewed the documentation and fixed the link. Closing the issue.
