### ISSUE TITLE
What are the guardrails?

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#63]
Issue in ./help/query-service/clients/overview.md

What is the query timeout and maximum number of records or size of data that can be returned in a query?

**Comment by djwendo** [comment]
Hi Nick, the Query Service team is working on this as part of https://jira.corp.adobe.com/browse/PLAT-83565. Please add any contributions to that ticket regarding the types of guardrails and details you would like to see.
