### ISSUE TITLE
Decision Service link click to incorrect page

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#64]
Decision Service link on this page: https://www.adobe.io/apis/experienceplatform/home/services.html
does not click through to decision service documentation, instead clicks through to https://experienceleague.adobe.com/#home

i assume should click to something like: https://experienceleague.adobe.com/docs/offer-decisioning/using/offer-decisioning-home.html?lang=en

**Comment by djwendo** [comment]
I believe I've fixed what needed to be fixed. Tracking in https://jira.corp.adobe.com/browse/PLAT-84038. Will update and close this issue once the resolution pushes to prod tomorrow morning.

**Comment by djwendo** [comment]
The link has been updated. http://www.adobe.com/go/decisioning-home-en now points to https://experienceleague.adobe.com/docs/offer-decisioning/using/offer-decisioning-home.html
