### ISSUE TITLE
required flowID parameter missing from example

### ISSUE THREAD

**Issue by bitsrfr** [AdobeDocs/experience-platform.en#65]
Issue in ./help/ingestion/tutorials/streaming-record-data.md

I found that when trying to "Ingest record data to the streaming connection" that I needed to add the flowID in the header section within the HTTP POST body.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-126086.

**Comment by vfalon** [comment]
We've updated the documentation with the missing info. Closing the issue.
