### ISSUE TITLE
Experience Event data limits

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/experience-platform.en#65]
Issue in ./help/profile/guardrails.md

These guardrails seem to outline the profile record data limits. But no mention is made of experience event limits or guardrails.

For example the docs says there is a 1mb limit on profile size. But the number of experience events for a profile far exceeds 1mb.

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-84329

**Comment by djwendo** [comment]
The guardrails documentation has been updated to better address these limits: https://experienceleague.adobe.com/docs/experience-platform/profile/guardrails.html?lang=en
