### ISSUE TITLE
over use of "automatically"

### ISSUE THREAD

**Issue by rishimittal2003** [AdobeDocs/experience-platform.en#66]
Issue in ./help/edge/data-collection/adobe-analytics/analytics-overview.md

"The Adobe Experience Platform Edge Network automatically maps many XDM variables automatically. The complete list of automatically mapped variables is listed here."

Too many "automatically". May be rephrase to: "The Adobe Experience Platform Edge Network maps many XDM variables automatically. The complete list of these variables is listed here."

**Comment by djwendo** [comment]
Thank you for reporting this. We will work to get the documentation updated.

Internally tracking in https://jira.corp.adobe.com/browse/PLAT-86583

**Comment by srhoades-adobe** [comment]
This issue has been fixed. Thank you.
