### ISSUE TITLE
No Client Secret in the UI for Trade Desk Integration

### ISSUE THREAD

**Issue by sahjain** [AdobeDocs/experience-platform.en#68]
Issue in ./help/destinations/catalog/advertising/tradedesk.md

At the following URL:
https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/tradedesk.html#activate-segments

The help portal says to enter "Client Secret: The clientSecret parameter used in the OAuth2 client credentials." to setup this destination. But there is no option to enter client secret in the AEP Trade Desk Destination UI.

![Screenshot at Feb 08 17-24-38](https://user-images.githubusercontent.com/78734556/107216280-8f4c8d80-6a32-11eb-8313-d21f90754158.png)

Can you please update the same to provide the correct guidelines.

**Comment by vgiurgiu** [comment]
@sahjain - thank you for reporting this. We're tracking the issue internally in https://jira.corp.adobe.com/browse/PLAT-86911 and will update the documentation shortly.

**Comment by vgiurgiu** [comment]
We confirmed with engineering that client secret is not needed and removed this part from the documentation: 
`Client Secret: The clientSecret parameter used in the OAuth2 client credentials.`

Closing the issue, thanks again for reporting it.
