### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#69]
Issue in ./help/data-prep/dates.md

In the documentation it says the following.

"When string fields from incoming data are mapped to date fields in schemas using Experience Data Model (XDM), the date format should be explicitly mentioned."

My question is, how does one explicitly mention the date format?

For example if I am uploading a CSV file with a date column.
01-03-2021 being an example column value.

How in the CSV do I explicitly mention the date format?

**Comment by djwendo** [comment]
Tracking in: https://jira.corp.adobe.com/browse/PLAT-87608
Please feel free to provide additional comments there.
