### ISSUE TITLE
Relationship schema setting guidance is incomplete

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#7]
Issue in help/xdm/tutorials/relationship-ui.md

The documentation says that the relationship schema does not need to be enabled for profile and provides no guidance that the reference dataset needs to be enabled for profile.

Need better guidance on how to configure the relationship schema.

**Comment by djwendo** [comment]
@pnolan89 FYI. Updates requested to relationship UI tutorial.

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-63639

**Comment by pnolan89** [comment]
Tutorial has been updated: https://docs.adobe.com/content/help/en/experience-platform/xdm/tutorials/relationship-ui.html
