### ISSUE TITLE
Trailing comma in patch syntax causes error.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#7]
Issue in ./help/catalog/datasets/enable-upsert.md

Having this trailing comma in the patch syntax causes an error. If you remove the trainling comma it works fine.

https://share.getcloudapp.com/yAukrGoR

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-113829.

**Comment by vfalon** [comment]
@nhecht The docs were updated and this issue is now fixed. Thank you for raising this!
