### ISSUE TITLE
Data format in header should be described

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#70]
Issue in ./help/data-prep/dates.md

It would be helpful to describe that by adding the date format to the header of the file being ingested that the date format will be recognized, as an alternative to describing how the compute function.

We should also add detail about what date format is required. and how the mapper functions or the header syntax can be used to ensure the date is ingested correctly.

**Comment by djwendo** [comment]
Tracking internally in: https://jira.corp.adobe.com/browse/PLAT-87608
