### ISSUE TITLE
Correction in the data ingestion and segment evaluation

### ISSUE THREAD

**Issue by praveenpenupati** [AdobeDocs/experience-platform.en#71]
Issue in ./help/segmentation/ui/streaming-segmentation.md

In the second Note on this page, it reads '**Segments** ingested using a batch-based source will be evaluated nightly, even if it qualifies for streaming segmentation.'

I presume this should read 'Data' ingested using a batch-based source and not 'Segments'

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-126085.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the necessary changes. Closing the issue now.
