### ISSUE TITLE
What Target features does Web SDK Support?

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#71]
Issue in ./help/edge/personalization/adobe-target/target-overview.md

I'd like to be able to have a table which i can quickly scan to see which Target features are currently supported by Web SDK and which aren't so I can evaluate if I am ready to upgrade. Source data is here: https://github.com/adobe/alloy/projects/5 so at the very minimum it would be good to have a link, however a formatted table on the Target Overview page would make it much easier.

**Comment by djwendo** [comment]
Created https://jira.corp.adobe.com/browse/PLAT-87609 to track this update. Please feel free to add additional comments or questions there.

**Comment by djwendo** [comment]
Documentation has been updated and Jira ticket has been closed.

Doc update: https://experienceleague.adobe.com/docs/experience-platform/edge/personalization/adobe-target/target-overview.html?lang=en#personalization
