### ISSUE TITLE
Link to GCP authentication guide is too generic

### ISSUE THREAD

**Issue by skolodyazhnyy** [AdobeDocs/experience-platform.en#72]
Issue in 
- ./help/sources/tutorials/ui/create/cloud-storage/google-cloud-storage.md
- ./help/sources/tutorials/api/create/cloud-storage/google.md

Hey,

I noticed, the documentation mentions [server-to-server authentication guide](https://cloud.google.com/docs/authentication/production) which describes different methods to authenticate in GCP, but none of them is correct for Google Cloud Storage. The link should lead to [HMAC Keys documentation](https://cloud.google.com/storage/docs/authentication/hmackeys) and ideally guide should explain that user has to perform following steps:

- Go to Google Cloud Storage browser
- Click Settings
- Click Interoperability
- Create Access Key for service account

**Comment by djwendo** [comment]
Thank you for reporting this issue, and update will be made available soon.  

Tracking the resolution internally here: https://jira.corp.adobe.com/browse/PLAT-89712.

**Comment by djwendo** [comment]
Google Cloud Storage source docs have been updated. Expanded steps for interoperability and HMAC keys in the [main overview](https://experienceleague.adobe.com/docs/experience-platform/sources/connectors/cloud-storage/google-cloud-storage.html?lang=en#connect-google-cloud-storage-to-platform), and also elaborated on credentials in both the [API guide](https://experienceleague.adobe.com/docs/experience-platform/sources/api-tutorials/create/cloud-storage/google.html?lang=en#create-a-connection) and [UI guide](https://experienceleague.adobe.com/docs/experience-platform/sources/ui-tutorials/create/cloud-storage/google-cloud-storage.html?lang=en#ui-tutorials).
