### ISSUE TITLE
Migrating to FPID Diagram Error

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/experience-platform.en#72]
Issue in ./help/edge/identity/first-party-device-ids.md
RE: the diagram under: Migrating to first-party device IDs
The ID hierarchy section says ECID takes priority over FPID when both are sent. If this is true, I think visit five in the diagram should list ECID as the identifier.

**Comment by ryrob30** [comment]
Perhaps I miss read it. Maybe the implication is that the ECID 678 is based off of the FPID? Either way that isn't super clear.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-126083.

**Comment by vfalon** [comment]
We've reviewed the documentation and updated the diagram.
