### ISSUE TITLE
In accurate statement on generation of ECID

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/experience-platform.en#73]
Issue in ./help/collection/visitor-identification-fpid.md

This line in the 5th paragraph of the overview seems inaccurate: Therefore, the Edge Network will use the ECID already provided and will not compute one from the given FPID.
If no ECID is generated for the FPID sent then the scenario described here ([when to set the cookie](https://experienceleague.adobe.com/docs/experience-platform/edge/identity/first-party-device-ids.html%3Flang%3Dzh-Hant#when-to-set-the-cookie)) would not work right?

For the Scenario described in the link to be true wouldn't the ECID need to be computed from the FPID whenever it is sent, even if the primary ECID is the one explicitly passed?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-126082.

**Comment by vfalon** [comment]
We have reviewed the documentation and clarified the referenced information. Thanks again for raising this! Closing the issue.
