### ISSUE TITLE
URL of page called "latest"

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#73]
Issue in ./help/release-notes/latest/latest.md
As soon as new release notes come out for the next month, any links made to this month's release notes are no longer valid! 
If would be good if the link to the "latest" page would redirect to the latest month page, which would then work "forever" to get the release notes for that month.  

PS: I am using my personal Github account to create this note, but I'm an Adobe employee.  How can I log into GitHub with my adobe account or link the org to my personal account?  

As TAMs, we are providing customer with personalized release notes and it would be great if the links to release notes of any particular month will work forever.

**Comment by djwendo** [comment]
Hi @awiddie , thanks for logging this issue. Tracking in Jira here: https://jira.corp.adobe.com/browse/PLAT-90394

Please provide additional comments or feedback in the ticket.

**Comment by djwendo** [comment]
We have addressed this issue by adding a separate md page for each individual month, allowing users to grab the permanent link to a specific monthly release at the time of publication OR use the "latest" URL to always arrive at the current release notes.

![image](https://user-images.githubusercontent.com/35348791/116762346-fb55e680-a9ce-11eb-8820-5f52642a42ba.png)
