### ISSUE TITLE
Create target dataset is not having complete information

### ISSUE THREAD

**Issue by Kalaiyarasan01** [AdobeDocs/experience-platform.en#74]
Issue in ./help/sources/tutorials/api/collect/streaming.md

Please update this page similar to 
https://experienceleague.adobe.com/docs/experience-platform/catalog/api/create-dataset.html?lang=en#api

**Comment by djwendo** [comment]
Thank you for reporting this. 

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-96011.

**Comment by carlojavier** [comment]
@Kalaiyarasan01 Looking for some clarification here. The "create a target dataset" call in [./help/sources/tutorials/api/collect/streaming.md](https://experienceleague.adobe.com/docs/experience-platform/sources/api-tutorials/collect/streaming.html?lang=en#create-a-target-dataset) is already very similar to the "create a dataset" call in in the [Catalog and Datasets doc...](https://experienceleague.adobe.com/docs/experience-platform/catalog/api/create-dataset.html?lang=en#api). Do you mean to just remove the identity and profile tags in the "create a target dataset" version of the call? Pls lmk and I can make the update.

**Comment by djwendo** [comment]
The documentation has been updated to replicate the content from one page to the other. If additional changes are required, please lot a new github issue.
