### ISSUE TITLE
Table for functions isn't rendering correctly

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#75]
Issue in ./help/data-prep/functions.md

The function table isn't rendering as a table, but just shows pipe characters as text between columns.  Difficult to read.  Doesn't work in Chrome nor in Safari.

**Comment by djwendo** [comment]
Thank you for reporting this issue. The table has been fixed and is now rendering properly.
https://experienceleague.adobe.com/docs/experience-platform/data-prep/functions.html
