### ISSUE TITLE
Clarification on timestamp field

### ISSUE THREAD

**Issue by woolleyadobe** [AdobeDocs/experience-platform.en#76]
As per this JIRA ticket (https://jira.corp.adobe.com/browse/PLATIR-13246), it would be good to clarify that the timestamp field can only represent the observation of an event and be in the past.

Issue in ./help/xdm/classes/experienceevent.md

**Comment by djwendo** [comment]
Created https://jira.corp.adobe.com/browse/PLAT-96013 to track documentation updates.

**Comment by djwendo** [comment]
The documentation has been updated to clarify the timestamp field: https://experienceleague.adobe.com/docs/experience-platform/xdm/classes/experienceevent.html
