### ISSUE TITLE
Add context to the idea of "negation"

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#77]
Issue in ./help/segmentation/ui/edge-segmentation.md

This document references a "negation" scenario.
This is not immediately intuitive to me what this means.

Can we add further context or an example what negation means?

"Negation | If a query contains a negation, it cannot be evaluated using edge segmentation."

**Comment by djwendo** [comment]
Tracking documentation update here: https://jira.corp.adobe.com/browse/PLAT-96014

@nhecht please provide any additional information in the Jira ticket. Thanks!

**Comment by djwendo** [comment]
The documentation has been updated and is now live: https://experienceleague.adobe.com/docs/experience-platform/segmentation/ui/edge-segmentation.html?lang=en#next-steps
