### ISSUE TITLE
link on this page doesn't go to privacy service as it shulld

### ISSUE THREAD

**Issue by kfoster-dx** [AdobeDocs/experience-platform.en#78]
Issue in ./help/profile/privacy.md

Bad link on this lline:

Privacy Service: Manages customer requests for accessing, opting out of sale, or deleting their personal data across Adobe Experience Cloud applications.

https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html?lang=en#getting-started

**Comment by djwendo** [comment]
Thank you for reporting this. Tracking the update in https://jira.corp.adobe.com/browse/PLAT-96599

**Comment by djwendo** [comment]
This has been updated and is now linking correctly: https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html?lang=en#getting-started
