### ISSUE TITLE
Required Field Contradiction

### ISSUE THREAD

**Issue by jm-adobe** [AdobeDocs/experience-platform.en#78]
Issue in ./help/edge/data-collection/track-links.md

The top of the page mentions that [`web.webInteraction.name` is a required field](https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/track-links.html?lang=en#:~:text=There%20are%20three%20required%20variables), but further down it specifically mentions that you can [unset that value](https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/track-links.html?lang=en#:~:text=options.xdm.web.webInteraction.name%20%3D%20undefined%3B) to instead have it default to `web.webInteraction.URL` .

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-128017.

**Comment by vfalon** [comment]
Documentation updated to not mark the `name` field as required. Closing this issue.
