### ISSUE TITLE
Undocumented error code XDM-1413-400

### ISSUE THREAD

**Issue by selectdistinctuser** [AdobeDocs/experience-platform.en#79]
I get the error type http://ns.adobe.com/aep/errors/XDM-1413-400 with detailed message:
`Cannot merge incompatible data types. The path ... has already been defined in schema (id=) using a different data type. Types: object, string"`
It doesn't include id of conflicting schema and not sure why I can't have a field with the same name and different datatype on custom classes that have no union relation to the conflicting schema.

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-128019.

**Comment by vfalon** [comment]
Hi @teliadam. We're still investigating this issue and we have a few questions:

- Could you provide some further information about the schemas you are using and their relationships?
- What particular actions are triggering the error?

**Comment by selectdistinctuser** [comment]
Hi @vfalon, let's say I have a schema based on XDM Individual Profile with a custom Name attribute, which has a custom datatype. Then I create an unrelated schema which will be a lookup for some event so I create class called Hotel and try to add a Name attribute with String type. The error is triggered when I try to save this in the UI or do the create request through Schema Registry API.

**Comment by vfalon** [comment]
Hi @teliadam! We've added the error code to the documentation:https://experienceleague.adobe.com/docs/experience-platform/xdm/troubleshooting-guide.html#cannot-merge-incompatible-data-types.

However, our engineering team is still investigating this issue and would need your Org ID and sandbox information for further investigation.

**Comment by selectdistinctuser** [comment]
Hi @vfalon, this is not specific to just one sandbox, because I reproduced the error using 2 new schema from scratch. The description you referenced says:
> All Profile-enabled schemas belonging to the same class must be able to merge together in order to construct the union schema for that class.

But this merge error happens to any schema even if they don't belong to the same class or are not profile-enabled.

**Comment by vfalon** [comment]
Hi @teliadam. Since the documentation part of this issue was solved by the documentation update with the missing error code, I will go ahead and close this issue now.

If you need to dig deeper into the technical side of things, we recommend getting in touch with our technical support team so they can investigate further.

Thanks!
