### ISSUE TITLE
XDM Individual Profile - type not defined and not enabled for profile

### ISSUE THREAD

**Issue by alberto-decaro** [AdobeDocs/experience-platform.en#79]
Hi team.
The following article describe how to create a dataset suitable for an audience export:
**https://experienceleague.adobe.com/docs/experience-platform/segmentation/tutorials/create-dataset-export-segment.html?lang=en#getting-started**

The process requires to create a dataset based on the XDM Individual Profile Union Schema.
In two AEP instances I am facing the following:
1. Creating a dataset based from schema
2. Searching for XDM Individual Profile
3. The reported XDM individual Profile:

- Reports no type, and specifically not the expected Union type.
- Reports "Not enabled" for profile, and profile enable toggle is not available.

Attaching references to the following AEP tenats:
- experienceplatform
- sisalspa

![image](https://user-images.githubusercontent.com/2655809/118010114-ff7af000-b34e-11eb-830f-fb1e95032173.png)
![image](https://user-images.githubusercontent.com/2655809/118011991-e4a97b00-b350-11eb-9087-75ef22ab4caf.png)

Are there any specific requirements or provisioning condition not mentioned in the documentation?

Thanks,
Alberto

Issue in ./help/segmentation/tutorials/create-dataset-export-segment.md

**Comment by djwendo** [comment]
Thanks for your question, we are reviewing the documentation and will provide updates as soon as possible.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-97664

**Comment by djwendo** [comment]
The documentation has been updated and is now available on Experience League: https://experienceleague.adobe.com/docs/experience-platform/segmentation/tutorials/create-dataset-export-segment.html
