### ISSUE TITLE
Add note to streaming segmentation to call out dependancy on streaming data into AEP

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#8]
Issue in ./help/segmentation/ui/streaming-segmentation.md

could we add the same Note on this page that is also found here: 
https://experienceleague.adobe.com/docs/experience-platform/segmentation/api/streaming-segmentation.html?lang=en

More specifically, a note calling out the need for streamed data:
"Streaming segmentation can only be used to evaluate data that is streamed into Platform. In other words, data ingested through batch ingestion will not be evaluated through streaming segmentation, and will be evaluated along with the nightly scheduled segmented job."

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-113905.

**Comment by vfalon** [comment]
@iandejong The documentation was updated with the note you mentioned. Closing this issue.
