### ISSUE TITLE
Small issue where a response is not highlighted in bold

### ISSUE THREAD

**Issue by vgiurgiu** [AdobeDocs/experience-platform.en#8]
Issue in help/xdm/tutorials/create-schema-api.md

Minor issue. The response in https://docs.adobe.com/content/help/en/experience-platform/xdm/tutorials/create-schema-api.html#look-up-a-schema is not in **bold** because of an unnecessary extra space.

**Comment by djwendo** [comment]
@pnolan89 FYI. Minor edit to tutorial for creating a schema using the API.

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-63637

**Comment by pnolan89** [comment]
This was addressed in the following PR: https://git.corp.adobe.com/AdobeDocs/experience-platform.en/pull/738

This issue can be closed.
