### ISSUE TITLE
link to PowerBI directs to looker.com website which is a Google Cloud Platform link

### ISSUE THREAD

**Issue by MaximeFoutrel** [AdobeDocs/experience-platform.en#80]
Issue in ./help/query-service/clients/power-bi.md

The link used in the first Note section "This guide assumes you already have access to Power BI and are familiar with how to navigate its interface. More information about Power BI can be found in the **_official Power BI documentation_**." points to Google Cloud Platform BI tool as opposed to Microsoft Power BI tool.

Not sure how this ended up there... cannot be a mistake.

**Comment by djwendo** [comment]
We are reviewing the documentation and will provide an update as soon as possible.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-97667

**Comment by djwendo** [comment]
The documentation has been updated and the correct link to Power BI documentation is now present.

https://experienceleague.adobe.com/docs/experience-platform/query/clients/power-bi.html?lang=en#clients
