### ISSUE TITLE
anonimization is not an option for Real-time CDP

### ISSUE THREAD

**Issue by kfoster-dx** [AdobeDocs/experience-platform.en#81]
Issue in ./help/profile/privacy.md

We should not include anonymization as an option in the example as this isn't supported.

Would also be good if the page was made to be more explicit that this is for Adobe Experience Platform, and not just say "Platform" without the more complete name.

**Comment by djwendo** [comment]
Thank you for reporting this. We will review the documentation and publish updates as needed.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-97922

**Comment by djwendo** [comment]
The documentation has been updated and is now available here: https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html
