### ISSUE TITLE
Comma missing after "name": "Sample Query" in the Create Query Command

### ISSUE THREAD

**Issue by krishnakumar1990** [AdobeDocs/experience-platform.en#82]
Issue in ./help/query-service/api/queries.md

**Comment by djwendo** [comment]
Thank you for reporting this issue. The documentation will be updated as soon as possible.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-98613

**Comment by calebk1** [comment]
Documentation at the attached link updated: https://experienceleague.adobe.com/docs/experience-platform/query/api/queries.html
