### ISSUE TITLE
Prerequisites for RTCDP Adcloud Destination

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#82]
Issue in ./help/destinations/catalog/advertising/adobe-advertising-cloud-connection.md

can we clarify if customer also needs to be a LiveRamp customer to leverage this capability

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-128021.

**Comment by vgiurgiu** [comment]
@iandejong - we have clarified with the AdCloud team that the customer needing to also be a LiveRamp customer to leverage the AEP-> AdCloud integration is **not** a requirement. We have updated the prerequisites section of the page (https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/adobe-advertising-cloud-connection.html?lang=en#prerequisites) to mention this.

Closing this issue.
