### ISSUE TITLE
{ETAG} value - add more details about the format

### ISSUE THREAD

**Issue by gchungadobe** [AdobeDocs/experience-platform.en#83]
{ETAG} | Use the etag that you obtained in the previous step.

Add more details such as: 
Get {ETAG} from the response of the previous step (Create a Dataflow)
The response format will be have escaped quotes. 
You may have to use the unescaped values: 
Response example:
"etag": "\"7400453a-0000-1a00-0000-62b1c7a90000\""

Value to use in request:
"etag": "7400453a-0000-1a00-0000-62b1c7a90000"
In Postman, also include the quotes: "7400453a-0000-1a00-0000-62b1c7a90000"

**Comment by vfalon** [comment]
Hello @gchungadobe . Thanks for raising this. What documentation page does this refer to?

**Comment by vfalon** [comment]
The etag details were updated in the following articles:

- https://experienceleague.adobe.com/docs/experience-platform/destinations/api/connect-activate-batch-destinations.html?lang=en#activate-data
- https://experienceleague.adobe.com/docs/experience-platform/destinations/api/streaming-destinations.html?lang=en#activate-data

You can disregard my previous question. Closing this issue.
