### ISSUE TITLE
identity in array or map type fields

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#83]
Issue in ./help/identity-service/home.md

Question on the below. 
Can array fields be marked and processed for identity?
Can map type fields be marked and processed for identity?

"Marking XDM fields as identity
Any field of type string in schemas that implement either record or time series XDM classes can be labeled as an identity field. As a result, all data ingested into that field would be considered identity data."

**Comment by djwendo** [comment]
We will review the documentation and make updates to clarify the information as soon as possible.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-98614

**Comment by djwendo** [comment]
Content has been updated and is now live: https://experienceleague.adobe.com/docs/experience-platform/identity/home.html?lang=en#marking-xdm-fields-as-identity
