### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/experience-platform.en#84]
Issue in ./help/edge/data-collection/adobe-analytics/manually-mapping-variables.md

The word "Products" at the end of this sentence is a broken link. "Also, you can use a default set of actions and product lists to send or retrieve data with Adobe Experience Platform Web SDK. To do this, see Products."

**Comment by djwendo** [comment]
Thank you for reporting this. The documentation will be reviewed and updated as soon as possible.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-98615

**Comment by djwendo** [comment]
The link has been updated and is now linking as expected.

https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/adobe-analytics/manually-mapping-variables.html?lang=en
