### ISSUE TITLE
GAM360 Export type description

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#84]
Issue in ./help/destinations/catalog/advertising/google-ad-manager-360-connection.md

part of this documentation, i.e under Export type and frequency > table item > Export type > the description gives an example of email, phone, last name etc. and I’m not sure if that will confuse customers as the only editable field is the PPID and that should not be PII such as email, phone, name etc.
 
I understand it’s a generic explanation about profile-based export types from AEP but I would suggest we adjust re-word slightly in the context of the GAM destination, perhaps something like the following
 
"You are exporting all members of a segment, together with the applicable schema fields (for example your PPID), as chosen in the select profile attributes screen of the destination activation workflow."

thoughts?

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-128023.

**Comment by vgiurgiu** [comment]
We've reviewed the documentation and made the necessary changes. Closing the issue now. Thanks again for your support.
