### ISSUE TITLE
Can I change the name of the schema once it has been created/used?

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#85]
Issue in ./help/xdm/schema/composition.md

It would be good to add this info to the table of either allowed or breaking changes!  Someone from engineering added new schemas and datasets to the prod sandbox of my customer and they did not like the chosen naming and did not think they could change it themselves. I haven't tried it so I don't know if the system lets you make this change or not.

**Comment by djwendo** [comment]
Thank you for logging this issue. The documentation will be reviewed and updated as soon as possible.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-98616

**Comment by djwendo** [comment]
The documentation has been updated to provide more information: https://experienceleague.adobe.com/docs/experience-platform/xdm/schema/composition.html?lang=en#evolution
