### ISSUE TITLE
WEb SDK - mapping analytics data - broken link and not clear example

### ISSUE THREAD

**Issue by alberto-decaro** [AdobeDocs/experience-platform.en#86]
Hi team.
I am referencing the "Context data" section of the reported page.
1. The section features a snipped of JSON with a sample context data structure. Although it is not clear the relationship between such a JSON structure and the alloy methods. Should the context data JSON be included in the XDM argument of the alloy method? Should that be the first argument directly?
2. The "Product" link is broken:
![image](https://user-images.githubusercontent.com/2655809/120782985-db17cb00-c52a-11eb-902d-a37947a47793.png)

![image](https://user-images.githubusercontent.com/2655809/120783027-e8cd5080-c52a-11eb-9dcc-871b27200b61.png)

Thank you for your support.
Alberto

Issue in ./help/edge/data-collection/adobe-analytics/manually-mapping-variables.md

**Comment by djwendo** [comment]
This same issue was reported in GitHub Issue #84 - we are working to resolve.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-98615

**Comment by djwendo** [comment]
The link has been updated and is now linking as expected: https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/adobe-analytics/manually-mapping-variables.html?lang=en

The "Context data" JSON is still under review and being tracked internally here: https://jira.corp.adobe.com/browse/PLAT-98615

**Comment by vivasd** [comment]
Hi @alberto-decaro, thanks for calling this out. Regarding your first point this snippet is just there to show you what the context data will look like when its flattened. We just wanted to include this example as a reference and so you have an idea of what it will look like in your processing rule. This snippet doesn't need to be included anywhere. If you just map your data using XDM you should see it in processing rules.
