### ISSUE TITLE
Incorrect link to use-cases board"

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-platform.en#87]
Issue in ./help/edge/home.md

https://experienceleague.adobe.com/docs/experience-platform/edge/home.html?lang=en

The documentation mentions "use-cases board" that should explain the below.

-     Use Cases Not Yet Supported: These are use cases that are on our roadmap to be supported in the future.
-     Use Cases In Progress: These are the use cases the team is currently working on completing for release.
-     Supported Use Cases: These are the use cases that are supported and work today.
-     Use Cases We Won’t Support: These are the use cases we have made a decision not to support.

However the link takes to the Kanban board showing backlog, tickets in progress and completed. 

How do i find out "Use Cases We Won’t Support"?

**Comment by djwendo** [comment]
Thank you for reporting this issue. The documentation will be reviewed and updated accordingly.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-99040

**Comment by djwendo** [comment]
The documentation has now been updated to correctly link to the [Supported use cases](https://experienceleague.adobe.com/docs/experience-platform/edge/fundamentals/supported-use-cases.html?lang=en) documentation.
