### ISSUE TITLE
GAM 360 PPID > Allow List section suggestions

### ISSUE THREAD

**Issue by iandejong** [AdobeDocs/experience-platform.en#87]
Issue in ./help/destinations/catalog/advertising/google-ad-manager-360-connection.md

some minor suggestions looking at the "Allow-listing" section of this page
- GAM 360 publishers can now link their own DMPs, see: https://support.google.com/admanager/answer/3289669?hl=en
- Then "If you need to contact Google regarding this process, please provide the following:"
   - 'Network ID', I suggest using "Network code: this is your Google Ad Manager network identifier, found under 'Admin --> Global settings' - as well as in the URL".
   - Also: "Audience Link ID: this is a specific identifier associated with your Google Ad Manager network (not your Network code), also found under 'Admin --> Global settings."

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-128024.

**Comment by vgiurgiu** [comment]
We've reviewed the documentation and made the necessary changes. Closing the issue now. Thanks again for your support.
