### ISSUE TITLE
Self-serve applications don't include Magento, Marketo or Workfront

### ISSUE THREAD

**Issue by MicahThorner** [AdobeDocs/experience-platform.en#88]
Issue in ./help/privacy-service/experience-cloud-apps.md 

For the self-service applications that don't use the Privacy Service, Magento, Marketo and Workfront are omitted from the list. 

For Magento the link is:
https://devdocs.magento.com/compliance/industry-compliance.html

For Workfront: 
https://app-eu.onetrust.com/app/#/webform/61fd4bf7-6e31-496d-8a16-aaca0b9d1397

For Marketo
https://developers.marketo.com/rest-api/lead-database/

Also, it looks like the links below from the Experience League for AEM and AEP aren’t working.

**Comment by djwendo** [comment]
Thank you for reporting this issue. We will review and update the documentation.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-99746

**Comment by djwendo** [comment]
The table has been updated on Experience League: https://experienceleague.adobe.com/docs/experience-platform/privacy/experience-cloud-apps.html?lang=en#self-serve
