### ISSUE TITLE
Incorrect Destination Listed

### ISSUE THREAD

**Issue by JackRoy00** [AdobeDocs/experience-platform.en#89]
Issue in ./help/destinations/catalog/advertising/bing.md

'The Trade Desk' is mentioned within the 'Supported Identities' section when it should be Bing.

**Comment by djwendo** [comment]
Thank you for reporting this issue. We will review and update the documentation.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-99745

**Comment by vfalon** [comment]
Documentation updated: https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/bing.html?lang=en

**Comment by JackRoy00** [comment]
Hi Wendy,

Just checked the documentation and I still see the error on the page – not sure if it takes time to update onsite. See below:

[Graphical user interface, text, application, email  Description automatically generated]

Best,

Jack Roy  |  Associate Consultant – Solution Delivery  |  Adobe  |  +1 646 678 2075  |  ***@***.***


From: Wendy Braun ***@***.***>
Reply-To: "AdobeDocs/experience-platform.en" ***@***.***>
Date: Tuesday, June 22, 2021 at 8:47 AM
To: "AdobeDocs/experience-platform.en" ***@***.***>
Cc: Jack Roy ***@***.***>, Author ***@***.***>
Subject: Re: [AdobeDocs/experience-platform.en] Incorrect Destination Listed (#89)


Closed #89<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdobeDocs%2Fexperience-platform.en%2Fissues%2F89&data=04%7C01%7Cjaroy%40adobe.com%7Cd881f41e3feb44f15d7a08d93594f8fc%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637599736214975814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gyR%2Bpo9iUUNtsf6w66hX9XNFNDkSPT2GXTKvb1iT45A%3D&reserved=0>.

**Comment by vgiurgiu** [comment]
@JackRoy00 - thanks again for reporting this issue. I can confirm that the Microsoft Bing documentation page has been updated with your suggestion (see below). 

![microsoft-bing-updated-docs](https://user-images.githubusercontent.com/19704189/122967956-05ee8580-d359-11eb-92ec-347987738641.png)

Please try clearing your cache or opening the [documentation page](https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/advertising/bing.html?lang=en) in incognito mode.
