### ISSUE TITLE
Recs examples

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#89]
In "How do I use Target Recommendations" the examples should show "entity.id" and "entity.name" instead of "entity.productId" and "entity.productName". These are the reserved param names for these common fields.

Issue in ./help/edge/personalization/adobe-target/web-sdk-atjs-comparison.md

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-128911.

**Comment by vfalon** [comment]
Updated the docs with the correct parameter names. Closing the issue.
