### ISSUE TITLE
Example of what segment export can look like

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#9]
Issue in help/segmentation/tutorials/export-data.md

I'd like to see an example of what the data in the segment export looks like so I can have a better idea of what the format of the segment export is like.

**Comment by djwendo** [comment]
Tracking in https://jira.corp.adobe.com/browse/PLAT-58730

**Comment by vgiurgiu** [comment]
@djwendo - we updated the documentation to address https://jira.corp.adobe.com/browse/PLAT-58730. At your convenience, you can go ahead and close this issue.
