### ISSUE TITLE
Per Engineering this limit should be 1500 segments per sandbox

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#9]
Issue in ./help/profile/guardrails.md

The documentation says there are 10,000 segments per sandbox, but per engineering this should be 1500. But will be increasing over the coming months.

Segments per sandbox | 10,000 | Soft

**Comment by vgiurgiu** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-114060.

**Comment by vfalon** [comment]
We've validated this information with our product and engineering teams, and the 10000 limit is correct. Closing this issue.
