### ISSUE TITLE
Customer attributes data source additional details needed

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#91]
Issue in ./help/sources/tutorials/ui/create/adobe-applications/customer-attributes.md

Can we add detail to this page about what target dataset and schema the customer attributes source uses. As well as how to configure it for profile ingestion and whether identities need to be manually configured or whether the source inherits the identity settings from the Customer Record Service configuration.

**Comment by djwendo** [comment]
Thanks for reporting this issue. We will review the documentation and publish updates shortly.

Tracking internally: https://jira.corp.adobe.com/browse/PLAT-101351

**Comment by djwendo** [comment]
Documentation has been updated and is now live on Experience League: https://experienceleague.adobe.com/docs/experience-platform/sources/connectors/adobe-applications/customer-attributes.html
