### ISSUE TITLE
First two examples of productListItems

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/experience-platform.en#95]
The first two examples of productListItems are described as "productView event" but is the second one showing that or an add to cart event?

Issue in ./help/edge/data-collection/collect-commerce-data.md

**Comment by djwendo** [comment]
Thank you for reporting this issue. Tracking internally in https://jira.corp.adobe.com/browse/PLAT-102540

**Comment by djwendo** [comment]
The documentation has now been updated to show the proper events.
https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/collect-commerce-data.html?lang=en#examples
