### ISSUE TITLE
I think this may be the wrong page.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#95]
Issue in ./help/destinations/ui/activate-segment-streaming-destinations.md

This page shows details about mapping attributes to the destination which seems more relevant to the profile and segment activation route documented here - https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-streaming-profile-destinations.html?lang=en

Where as the page linked (https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-streaming-profile-destinations.html?lang=en) seems more to outline the segment only activation.

Is this suppose to be switched the titles seem to be they should be switched.

**Comment by vgiurgiu** [comment]
Hey @nhecht  - thanks for reporting this. The pages are correct, albeit they might need some screenshot updates (to be handled in PLAT-129793), here is more context: 

1. **Activate audience data to streaming segment export destinations** - https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-segment-streaming-destinations.html?lang=en - there is a mapping step here. For some of the destinations in this category, you are able to map attributes or identity namespaces from the source schema to the target identity accepted by the destination. We call out at the top of the mapping section that this step is only available for some destinations (https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-segment-streaming-destinations.html?lang=en#mapping)
2. **Activate audience data to streaming profile export destinations** - https://experienceleague.adobe.com/docs/experience-platform/destinations/ui/activate/activate-streaming-profile-destinations.html?lang=en  - we need to update the screenshots here to account for the fact that the step is not called **Select attributes** anymore, but rather **Mapping**. 

Closing this issue, please reopen if you have further questions.
