### ISSUE TITLE
Pls update the screenshot for the privacy UI

### ISSUE THREAD

**Issue by awiddie** [AdobeDocs/experience-platform.en#96]
Issue in ./help/profile/privacy.md

The current screenshot does not show a checkbox for identity.  That was added earlier this year. The text on the page refers to identity, but this screenshot doesn't show it (older version).  This same screen would also need updating on the Data Lake deletion page.

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-129410.

**Comment by vfalon** [comment]
We've updated the screenshots in multiple documentation pages:

 https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html#using-the-ui
 https://experienceleague.adobe.com/docs/experience-platform/catalog/privacy.html#using-the-ui
 https://experienceleague.adobe.com/docs/experience-platform/identity/privacy.html#using-the-ui

Closing this issue.
