### ISSUE TITLE
more clarity needed on the soft deletion timelines

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-platform.en#97]
Issue in ./help/profile/privacy.md

As per our [documentation](https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html?lang=en#delete):
_When Experience Platform receives a delete request from Privacy Service, Platform sends confirmation to Privacy Service that the request has been received and affected data has been marked for deletion. The records are then removed from the Data Lake or Profile store once the privacy job has completed. While the delete job is still processing, the data is soft-deleted and is therefore not accessible by any Platform service._

**Question: When exactly does the soft deletion happen? Is this immediately after the job is created? Can we assume that as soon as we get the privacy job ID back from the API call, profile will not be part of any export segment?**

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-129756.

**Comment by vfalon** [comment]
We've updated the documentation with more detailed information about deletion of privacy requests.

https://experienceleague.adobe.com/docs/experience-platform/catalog/privacy.html#delete-request-processing
https://experienceleague.adobe.com/docs/experience-platform/identity/privacy.html#delete-request-processing
https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html#delete

Closing the issue.
