### ISSUE TITLE
We should show a screen shot of the Hotels schema identity being configured 

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/experience-platform.en#97]
Issue in ./help/xdm/tutorials/relationship-ui.md

We should show a screen shot of the Hotels schema identity being configured

**Comment by djwendo** [comment]
Thank you for reporting this issue. Tracking in https://jira.corp.adobe.com/browse/PLAT-102538

**Comment by djwendo** [comment]
The documentation has been updated and is now live on Experience League: https://experienceleague.adobe.com/docs/experience-platform/xdm/tutorials/relationship-ui.html
