### ISSUE TITLE
Incorrect video for Facebook Destination Setup

### ISSUE THREAD

**Issue by rishimittal2003** [AdobeDocs/experience-platform.en#98]
Issue in ./help/destinations/catalog/social/facebook.md

The video attached is for LinkedIn

**Comment by vgiurgiu** [comment]
Thank you for reporting this issue. We will review and update the documentation.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-102516

**Comment by vgiurgiu** [comment]
@rishimittal2003 - the video on the page describes how to set up a social destination. While it takes LinkedIn as an example, the steps are similar across all social destinations, which currently include LinkedIn, Facebook, and Google Customer Match. 

We updated the Facebook documentation page to highlight that the video applies to all social destinations: https://experienceleague.adobe.com/docs/experience-platform/destinations/catalog/social/facebook.html?lang=en#connect-destination

Thanks again for reporting this.

**Comment by rishimittal2003** [comment]
That makes sense. Thanks !!
