### ISSUE TITLE
Need more clarity on "chsnges to profile post privacy job creation"

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-platform.en#98]
Issue in ./help/profile/privacy.md

As per our [documentation](https://experienceleague.adobe.com/docs/experience-platform/profile/privacy.html?lang=en#submit):
It is also important to note that the amount of time a privacy request can take to complete cannot be guaranteed. If changes occur in your Profile data while a request is still processing, whether or not those records are processed also cannot be guaranteed.

Questions

In such scenarios what records are not processed?
If we ingest an event to the profile enabled dataset after the privacy job has been created, will just that event not be processed or the complete profile will not be processed?

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in PLAT-129907.

**Comment by vfalon** [comment]
We've reviewed the documentation and made the necessary updates. Closing this issue.
