### ISSUE TITLE
Where is Customer ID used?

### ISSUE THREAD

**Issue by rishimittal2003** [AdobeDocs/experience-platform.en#99]
Issue in ./help/destinations/catalog/advertising/google-dv360.md

In the list of Prerequisites, it is not clear where the Customer ID will be used. Also, the Account ID information must be fetched from Google Representative. Not sure how Adobe client care or Adobe representative can help.

**Comment by vgiurgiu** [comment]
Thank you for reporting this issue. We will review and update the documentation.

Internal tracking: https://jira.corp.adobe.com/browse/PLAT-102524

**Comment by vfalon** [comment]
We've updated the Google destinations pages with the correct Account and Customer IDs.
